### PR TITLE
Operation "Inbox" - to replace the "pending" lists

### PR DESCRIPTION
**Pull request by kytrinyx**
I think that ultimately we should implement the activity stream (https://github.com/exercism/exercism.io/issues/1899), which would allow granular subscriptions, however that is a huge undertaking, and I think that we could aim for a simpler solution in the shorter term, which would still be a _huge_ improvement over the current pending lists.

The inbox would be per language track. You would see a paginated list of all the exercises that you have access to, ordered in reverse chronological order by last activity (new submission or new comment).

This would allow a number of simplifications:

1. No more "state" field on submissions.
1. No more "state" field on exercises (it would be replaced by a flag for "archived", which defaults to false).
1. No more "muted submissions"

To simplify this implementation, we should have two additional tables:

- `views` -- Fields: user_id, exercise_id, last_viewed_at. Unique key on (user_id, exercise_id).
- `acls` (access control lists) -- Fields: user_id, track (e.g. "ruby"), problem (e.g. "bob")

We would write to the `views` each time someone visits an exercise.
We would write to the `acls` each time someone submits a solution.
We would update the last activity timestamp each time someone submits a solution or comments.

We also need to handle track mentors, who have access to all problems in their tracks. Perhaps we can use a cron job for this, checking for any new problems that they don't have access to, and add an entry for those problems.

**Step 1**

- [x] create database migration for views
- [x] create database migration for acls
- [x] create database migration to add `last_iteration_at` timestamp field to `user_exercises` table
- [x] deploy and migrate

**Step 2**

- [x] write to `views` each time someone visits an exercise
- [x] write to `acls` each time someone submits a solution
- [x] write to `user_exercises.last_iteration_at` when someone submits a solution
- [x] write cron job to migrate acls for track mentors
- [x] write rake tasks to migrate existing views based on looks
- [x] write rake tasks to migrate existing acls based on submissions
- [x] write rake task to migrate `last_iteration_at` based on submissions
- [x] oops - create database migration to add `last_activity_at` timestamp field to `user_exercises` table
- [x] deploy and migrate
- [x] configure cron job for `data:migrate:mentor_acls`

```
rake db:migrate data:migrate:viewed data:migrate:acls data:migrate:mentor_acls data:migrate:last_iteration
```

**Step 3**
- [x] write to `user_exercises.last_activity_at` when someone submits a solution or comments
- [x] write rake task to migrate `last_activity_at` based on submissions and comments
- [x] deploy and migrate

**Step 4**
- [ ] implement new inbox prototype
  - [x] data for sidebar (all the user's active tracks, with counts for total exercises and unread) - 4a585be48d
  - [x] data for list of exercises (exercise uuid, language, slug, with username and avatar) - 32a50d882
  - [x] route + view
- [ ] submit for review
- [ ] merge and deploy

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm going to submit this to master, since we're not linking to the pages anywhere. That way we can try out out in production, and perhaps someone can help me make it look usable.

**Comment by kytrinyx** [comment]
OK, take a look at this: http://exercism.io/tracks/assembly/exercises

It's, admittedly, very, very bare bones, because I don't know how to do front-end stuff, but the basic idea is there.

**Comment by kytrinyx** [comment]
A few things that I'll fix when I've had a break:

- [ ] pagination (elide so we don't have hundreds of links to pages)
- [ ] add the breakdown for each exercise in the current track (the one you're looking at)
- [ ] mark as read when you first submit, since you have already seen your solution at that point.

**Comment by tejasbubane** [comment]
@kytrinyx http://exercism.io/tracks/assembly/exercises is giving a 500 error.

**Comment by kytrinyx** [comment]
I'm not getting an error, I'll check the logs to see if I can find yours. What happens if you try a language that you have submitted exercises in?

**Comment by kytrinyx** [comment]
OK, I think I have the basic functionality worked out. Next I'm going to take a stab at the Minimum Viable CSS for this thing.

**Comment by jtigger** [comment]
excellent!  Loving the concept and look.  Huge step forward @kytrinyx!

What do you think of tacking on a "x days ago"?  It anchors the notion that this is an activity stream and conveys the volume.

I suspect a fewer folks will comment on something that was last touched 3 weeks ago than 3 days ago.  It is not so much to encourage or discourage.  It's a sense of "forthrightness" of the system to the user.

**Comment by kytrinyx** [comment]
Agreed, I have the timestamp in the data that the view gets, and I think we need to expose that.

**Comment by sguermond** [comment]
@kytrinyx It looks great! It would definitely drive me to interact more with others and look at their code. For a newbie, it makes the collaborative aspect of the website immediately visible, my first reaction was "Wow, look at all those people who are also working on this thing!" It's fantastic paired with the fact that you are now able to see other submissions before yours is marked as complete.

What do you think of by default marking items from before your submission as read and only marking the ones appearing after your submission as unread? Or a bulk "mark as read" action, since there are so many older submissions?

**Comment by kytrinyx** [comment]
OMG the timing :) I just deployed the bulk "mark all as read" about three minutes ago.

**Comment by sguermond** [comment]
Nice :D

**Pull request merged**
