### PR TITLE
Sass generates our CSS.  No need to track CSS

### PR DESCRIPTION
**Pull request by kotp**
The project `.gitignore` file ignores the CSS folder.

CONTRIBUTING.md makes a note to run compass to build the CSS files.

### CODE REVIEW

**Comment by kotp** [comment]
uh-hm.. apparently the CI does not do the required things.

**Comment by kotp** [comment]
Nope, that is not it.  Back to the drawing board.

**Comment by kytrinyx** [comment]
I don't have a proper build on Heroku, because of some non-standard stuff, and I didn't have the mental capacity to go figure out how to either fork the default heroku build, or reorganize the project to be able to use the default one. So until further notice, we're committing the generated CSS files.

**Comment by kotp** [comment]
Well, it does simplify some things to have them committed.  On my machine it does take a long time to generate them.

**Comment by kytrinyx** [comment]
Yeah, that makes a ton of sense. I really hope to get to the point soon where I can fix a lot of this.

**Pull request closed without merging**
