### PR TITLE
Sort participating users higher in user lookup

### LINKED ISSUE #1805: Sort participating usernames higher in auto-complete for @username
Auto complete should first suggest names that have commented on the current post. That has a much stronger possibility of a match than alphabetic order.

### PR DESCRIPTION
**Pull request by bluerogue251**
Closes #1805

When given a submission_id, order commenters higher than non-commenters
Match only by beginning of username, rather than anywhere in username
Change user lookup http request from POST to GET
All else being equal, sort alphabetically by username

At least two things I'm unsure of:
1. If passing the `submission_id` as I'm doing it (with the `data-sumission-id` attribute on an html element, and then looking it up in the DOM using Javascript) is the correct way of getting that info for the http request.
2. If it's ok to expose the `submission_id` in the html of the page delivered to the client, or if I should instead change it to use the `submission_key`.

### CODE REVIEW

**Comment by bluerogue251** [comment]
Looks like there are some frontend specs failing on Travis that I hadn't run on my local machine.  I'll learn how to run those and then update the PR.

**Comment by bluerogue251** [comment]
Ok updated.

**Comment by kytrinyx** [comment]
Thanks, @bluerogue251!

I think that using the `data` attribute to pass the value is correct. I'd like to use the submission key rather than the submission id, as I'd prefer to not expose guessable values.

**Comment by bluerogue251** [comment]
Sounds good! I updated the PR to only expose the `submission_key`, not the `submission_id`.

**Comment by kytrinyx** [comment]
Sweet, thanks so much!

**Comment by bluerogue251** [comment]
:-)

**Pull request merged**
