### PR TITLE
Add Breadcrumbs in Exercise detail

### PR DESCRIPTION
**Pull request by ElakiyaS**
This PR is referring this #3034.

3034_after_breadcrumbs
3034_before_breadcrumbs

### CODE REVIEW

**Comment by kytrinyx** [comment]
Would you please edit your pull request description to include a screenshot of the before/after? That would help with the review.

@troubalex Would you mind keeping an eye on this one?

**Comment by troubalex** [comment]
On it.

**Comment by troubalex** [comment]
@ElakiyaS Instead of ```>``` as the delimiter you could use an icon like this:

``` <i class="fa fa-caret-right"></i>```

You will have to play a bit with margins and font sizes though until you're happy with how it looks. I'd probably start with the same line-height as the text but 0.8em in font size, and then tweak.

**Comment by ElakiyaS** [comment]
@troubalex @kytrinyx  Sure will work on it.

**Comment by kytrinyx** [comment]
Would you post a screenshot when you're happy with what you've got?

**Comment by ElakiyaS** [comment]
@kytrinyx yeah.

**Comment by troubalex** [comment]
@ElakiyaS Is this ready for another review? Do you need any help?

**Comment by troubalex** [comment]
@kytrinyx I think this can be merged. We can always tweak more later.

Thanks, @ElakiyaS ❤️

**Comment by kytrinyx** [comment]
I'm resolving the conflict and merging this now. I'm so sorry it took so long!

Thank you for taking the time to work on this :heart:

**Comment by kytrinyx** [comment]
Merged in 8db4681ae45ce6bf7568a6840e9c3ed4bb5b2ac6

Thank you so much, @ElakiyaS

**Comment by ElakiyaS** [comment]
@kytrinyx Thanks :)

**Pull request closed without merging**
