### PR TITLE
Swap trackler into the activity streams

### PR DESCRIPTION
**Pull request by kytrinyx**
This helps with the refactoring in #3164

/cc @nickborromeo @mhelmetag @bernardoamc

### CODE REVIEW

**Comment by mhelmetag** [comment]
Looks like some `language` vs `track_id` type failures in travis...

**Comment by kytrinyx** [comment]
Oh, weird. I thought I ran the tests on this locally, but I must not have :( Bad, bad OSS maintainer!

**Comment by kytrinyx** [comment]
Weirdly, this is passing locally. Investigating.

**Comment by kytrinyx** [comment]
Oh, right. Found it (I needed to rebase this against the trackler base branch).

**Comment by mhelmetag** [comment]
LGTM!

**Pull request merged**
