### PR TITLE
Fixed styling bug. Fixes #2256

### LINKED ISSUE #2256: Invisible text on threads
pasted_image_3_23_15__10_03_am

### PR DESCRIPTION
**Pull request by joesiewert**
Set the label color to red. Let me know if you prefer a different color there.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks!

This is for the names, right? I'd prefer plain black.

**Comment by joesiewert** [comment]
It's for the author/peer labels. Here's a shot of my fix.

screen shot 2015-03-23 at 8 57 56 am

**Comment by kytrinyx** [comment]
Oh, right! Is there a light gray label?

**Comment by joesiewert** [comment]
Yep, I can switch it.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by joesiewert** [comment]
Fixed and squashed. I think it's ready.

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
