### PR TITLE
Architecture overview

### LINKED ISSUE #3253: Extract "Architecture Overview of Exercism" from CONTRIBUTING.md
*(part of a larger effort to overhaul documentation around contributing: exercism/discussions#73)*

[CONTRIBUTING.md#exercism-web-structure](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#exercism-web-structure) describes parts of the Exercism website.  This is a great start.

For first-time contributors, it can be immensely helpful to get a complete overview of all the parts of a system, how they work together *before* diving into the nitty-gritty of each of those parts.

- [ ] extract this section into a separate file: `docs/overview-of-exercism.md` (please use that name, other work (e.g. #3194) is referencing it).
- [ ] above those details, describe (at a high level) all of the components that make up Exercism, the online experience (your audience is a competent programmer, new to Exercism, appreciating links to frameworks and libraries):
  - the website
  - the CLI
  - the API
  - the trackler gem
  - include a section covering the domain concepts (steal from [`exercism/cli/README.md#domain-concepts`](https://github.com/exercism/cli#domain-concepts)).
- [ ] illustrate the core flows (sequence diagram?) in order to make clear the responsibilities of each component in the system:
  - how an exercise is fetched;
  - how an exercise is submitted;
  - how a solution is displayed on the website.

### PR DESCRIPTION
**Pull request by apostergiou**
This fixes #3253.

I'm not sure if the file name is correct, I used `overview-architecture.md` as mentioned in #3377.

- [x] Describe (at a high level) all of the components that make up Exercism
  - [x] the website
  - [x] the CLI
  - [x] the API
  - [x] the trackler gem
  - [x] include a section covering the domain concepts
- [x] Illustrate the core flows with a diagram

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you so much, @apostergiou! I just got in the door from some travel, and want to give this my full attention when my brain is fresh. I expect to spend my Saturday morning reviewing more meaty pull requests (like this one).

In the meanwhile...

@nickborromeo @Insti @kotp @bernardoamc if you have some extra cycles, would you take a look at this one?

**Comment by nickborromeo** [comment]
happy to help! 😄 I will check back when @apostergiou has made a substantial change.

**Comment by kotp** [comment]
So far so good @apostergiou

**Comment by kytrinyx** [comment]
This looks excellent! Would you give a shout when you're ready for a final review, @apostergiou?

**Comment by apostergiou** [comment]
Currently, I am working on the sequence diagram. The diagram will illustrate the core flows as it is suggested at #3253.

@kytrinyx I will give a shout when this is ready. Thanks!

**Comment by apostergiou** [comment]
Ready for review.

**Comment by kytrinyx** [comment]
Thank you so much @apostergiou!

**Comment by Insti** [comment]
Took me a while to get to it, but this is great @apostergiou :heart: thanks.

**Pull request merged**
