### PR TITLE
Change choco update to choco upgrade

### PR DESCRIPTION
**Pull request by jadevance**
DEPRECATION NOTICE - choco update is deprecated and will be removed or
 replaced in version 1.0.0 with something that performs the functions
 of updating package indexes. Please use `choco upgrade` instead.

### CODE REVIEW

**Comment by tejasbubane** [comment]
@jadevance Your PR has an extra commit from Katrina. Can you remove it and keep a single commit about choco?

**Comment by jadevance** [comment]
I'm sorry for messing this up. Would it be easiest to close this pull request and open a new one?

**Comment by catb0t** [comment]
You might be able to just rebase, but nobody's going to stop you opening a new PR if you want to.

**Comment by tejasbubane** [comment]
@jadevance Yes as @catb0t mentioned, it would be easiest to close this pull request and open a new one. But if you want to get your hands dirty with git, we would suggest you to [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing). Feel free to choose your way, no worries if you close this one.

**Comment by kytrinyx** [comment]
@jadevance This change looks good. I'll get this sorted and report back here. Thank you :heart:

**Comment by kytrinyx** [comment]
Merged in 619b008525508d11bbbe477dfe446d52eebf5b2d

**Pull request closed without merging**
