### PR TITLE
Added contribute page with implementations from another language

### PR DESCRIPTION
**Pull request by GustavoCaso**
#2762
@kytrinyx Here is my idea of the `contribute` page.

I'm open for design opinions, because I made it, but my design skill are quite non :-( , also I don't know if the `x-api` is deploy to the last version, the `readme` is not properly return, also I thought it would be nice to return the `track_name` from the `todo` endpoint.

You can access the page from the `language` page in the contribute section, there is a link
`languages/ruby/contribute`

### CODE REVIEW

**Comment by kytrinyx** [comment]
I just deployed x-api. Would you mind posting a screenshot of the page?

**Comment by GustavoCaso** [comment]
Sure @kytrinyx 
This is the page where is the link to access te contribute page 
image

And here in the page itself, I have paginated because it was to long sometimes and the user would have to scroll to see the content I have follow the language page design.

image

image

**Comment by GustavoCaso** [comment]
Also when we finish with this one I would like to start working on this one to continue with the contribution pages https://github.com/exercism/todo/issues/15

**Comment by kytrinyx** [comment]
For the main blurb, let's have two subtitles:

**Make up new exercises from scratch**
This can link to https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise (which we can improve over time)

**Port existing exercises to $LANGUAGE**
Then we can have some more explanatory text, and link to the list of missing implementations.

The list of missing exercises doesn't say which track it is.

I don't understand what is paginated. Could you elaborate, please?

**Comment by GustavoCaso** [comment]
Sure 

It is paginated because in the case of ruby there a lot of exercise to be implemented, so if the user would like to see of from the bottom, it will have to scroll back up, that way if we add the pagination, we avoid the scroll.

I could add the track name to this page as well.

Do you want me to remove the pagination ?

**Comment by kytrinyx** [comment]
I didn't understand that the pagination paginates the menu. The way it's implemented it looks like we're paginating the contents of the body, but it's not clear what that contents would be. I think it makes more sense to remove it.

**Comment by GustavoCaso** [comment]
The pagination tries to imitate the exercises page, the pagination actually
paginates the content, changing the problem to be  implemented, actually
the body, maybe placing the pagination closer to the list of problems
El 29/4/2016 9:18 p. m., "Katrina Owen" <notifications@github.com> escribió:

I didn't understand that the pagination paginates the menu. The way it's
implemented it looks like we're paginating the contents of the body, but
it's not clear what that contents would be. I think it makes more sense to
remove it.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/exercism/exercism.io/pull/2852#issuecomment-215853130>

**Comment by kytrinyx** [comment]
> The pagination tries to imitate the exercises page

The pagination on the exercises page doesn't change the left-hand menu. The menu stays the same. You're in "Go" and "Raindrops", for example, and then the content shows the first 50 exercises. Then you have pagination that gives you access to all of the other exercises.

**Comment by GustavoCaso** [comment]
@kytrinyx you are right it does not change the left-hand.

I can show you a couple of options, and we decide the best one.
I'm not very good with text, but here is the new one, tell me what you think.
image

And here are the options for the implementations page
option_1
As you can see the scroll is quite long and if the user wants to click the one from the bottom, it have to scroll up again.

option_2
With the pagination we avoid the extra scroll, but as you say it could confuse the users.

option_3
Here is another solution that came to my head, where we display each implementations, and clicking in the implementation we go to a show page with the information.

Or just come to my head seeing this video we could group by languages and show the different exercises implemented with does languages and if user click in the exercise it would go to the show page of that exercise.

I hope I have explain myself, english is not my native language, and sometimes I have problems expressing my ideas. I will try to show a gif with the last solution ASAP.

**Comment by kytrinyx** [comment]
I think you might be on to something by putting all of the exercises in a grid on one page.

I'm going to add the "blurb" to the "todo" output. That way we could have three or four across.


````
      bank-account

Bank accounts can be accessed in different ways at the same time.

     [readme] [json]
     [o] [o] [o] [o] [o]
````

The `[o]` could be little language track icons, which could link to the implementations.

What do you think? We wouldn't need to have the whole readme in the page, the blurb should describe enough to give an idea about the exercise.

**Comment by GustavoCaso** [comment]
@kytrinyx I like the idea, that way everything can be condensed in one page.

**Comment by kytrinyx** [comment]
BTW: I mentioned this conversation in today's "Behind the Scenes" newsletter. http://tinyletter.com/exercism/letters/exercism-it-s-about-the-conversations

**Comment by GustavoCaso** [comment]
Woow thanks @kytrinyx I'm honor. 

I will upload the new grid today after work, so we can keep discussing it .

**Comment by GustavoCaso** [comment]
@kytrinyx Here is how it looks like.
option_5


I have try to make each column the same height, but there are some exercises where the number of implementations are to many, maybe we could, just display does exercises which have `x` numbers of implementations.

Even doe we can display all in the same page, the design looks a little bit loaded.

What do you think ?

**Comment by kytrinyx** [comment]
I agree that at the moment this looks a little bit hard to navigate, but I think this is the right direction. Let's try a few tweaks to this.

First, use the name of the exercise, not the slug, and make it an h2 or h3. (the name of an exercise is `slug.split('-').map(&:capitalize).join(' ')`.

Also, let's make the language/track icons smaller (try half the current size?). Each track icon should have a title attribute that is the name of the language.

_Problem description_ would be better than "README", I think. And maybe we can try an icon (`info-circle`?) with a tooltip.

Instead of DATA let's try _shared test data_. And for an icon, let's try `list`.

**Comment by GustavoCaso** [comment]
Great lets try that.

I think the `todo` endpoint doesn't have the name of the language, just the slug, maybe is something I can include in the endpoint.

**Comment by kytrinyx** [comment]
I'll add it now.

**Comment by kytrinyx** [comment]
Actually: I'm going to both remove the README and add the language.

**Comment by kytrinyx** [comment]
Fixed; deploying now.

**Comment by GustavoCaso** [comment]
@kytrinyx This is with the new feedback, it is getting better for sure.

Tell what you think.
option_6

**Comment by kytrinyx** [comment]
Yes, this is looking very promising!

Next time would you please post a screenshot (not animated gif) of just the one page with the exercises to be implemented? It's very difficult to give feedback on it when it is flickering and moving and I have to wait for it to complete the cycle to look at it for a few more seconds.

Here's a screenshot of a part of the gif:

todo

I think that we've not found the right place yet for the readme and data. Can we try putting them in the top right corner next to the name of the exercise?

I also wonder if we need a h4 or something that says "Implementations" before all the icons.

Or perhaps we need to provide an explanation somewhere so that people know what they're looking at. I'm not sure.

**Comment by GustavoCaso** [comment]
@kytrinyx sure next time I will upload a screenshot.

Sure I think that the `readme` and the data is going to be better with in the exercise name.

Maybe removing that `h4` is an option, in the previous page there is an explanation of where the user is going.

I will make the changes ASAP and hope to aim for the good one. :)

**Comment by kytrinyx** [comment]
I expect us to link directly to this page in a lot of contexts, so it would be good to have enough explanation on the page to be able to understand it if you find it randomly from google.

**Comment by GustavoCaso** [comment]
👍  Got it so I will try to get a good explanation of where the user is.

**Comment by GustavoCaso** [comment]
@kytrinyx This could be the header, but we should add the repository url of the track in the `todo` endpoint

image


And here the exercises blocks

image

**Comment by kytrinyx** [comment]
Yeah, we should add the repository url.

Here's a suggestion for the introductory text:

> One of the easiest ways to add new exercises to the Ruby track is to translate them from other language tracks on Exercism. This page lists all of the exercises that exist on Exercism, but have not yet been implemented in Ruby.
> 
> [info icon] - the generic, language-independent problem description
> [list icon] - canonical test data (inputs and expectations)
> The language icons link to each existing implementation of the problem.
> 
> Once you've picked an exercise, follow the instructions in the [Contributing Guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track) and submit your pull request to the [Ruby track repository](https://github.com/exercism/xruby) on GitHub.

Contributing Guide url: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track

**Comment by GustavoCaso** [comment]
👍  great I will create a PR for adding the `repository_url`.

Also yes the text looks very concise and self explanatory, thanks for it.

I will change it ASAP.

**Comment by kytrinyx** [comment]
I just made the change to the x-api. I'll push it up now.

**Comment by GustavoCaso** [comment]
Great @kytrinyx.

Lets hope to finish with this one and continue with https://github.com/exercism/todo/issues/15

**Comment by kytrinyx** [comment]
Yes! This was a tricky one because it was not very well defined. Thanks so much for sticking with it through all the discussion and iterations.

**Comment by GustavoCaso** [comment]
Not a problem at all

**Comment by GustavoCaso** [comment]
image

What do you think ? @kytrinyx

**Comment by kytrinyx** [comment]
Now that I see it, I think that we need to turn the second and third lines into real sentences:

> The [info icon] icon links to the generic, language-independent problem description.
> 
> The [list icon] icon links to the canonical, test data for the problem.

Also, let's make the background white, not gray.

**Comment by GustavoCaso** [comment]
@kytrinyx I think this could be it

**Comment by GustavoCaso** [comment]
image

White Background 

image

And Mobile friendly

**Comment by kytrinyx** [comment]
Fabulous :) I'll pull this down and take one final look locally before merging, but this is looking great.

**Comment by kytrinyx** [comment]
Cool. I have a small text-only tweak.

The text in the "Contributing to Rust on Exercism" tab needs a little bit of extra attention.

Currently it says:

> *Want to help us*
> Make up new exercise from scratch
> You can follow this guide.
> Port existing exercise to Rust
> There are many already implemented exercises in other tracks, take a look to the complete list of exercises.

Let's change this to:

> **Help Add More Rust Exercises**
> 
> The easiest way to add new exercises is to translate existing exercises from other language tracks on Exercism. Here's the [full list of unimplemented exercises in Rust], along with links to all the existing implementations.
> 
> If you have an idea for a completely new exercise, you can follow [this guide] to add it to the site.

Once this is done, please rebase this onto master and squash the commits. Thanks!

**Comment by kytrinyx** [comment]
Since I haven't heard back, I'm going to go ahead and rebase, squash, and update the language locally.

**Comment by kytrinyx** [comment]
This is now merged in 17b8a6bbcd0c14b60d16828c251cac262cbc458d

**Comment by GustavoCaso** [comment]
@kytrinyx sorry I haven't answer I was on vacations.

Great to see that the feature is merged :)

What do you think If I start working on this one  https://github.com/exercism/todo/issues/15

**Comment by kytrinyx** [comment]
Yay, vacation sounds great :) I think that's a great idea.

Thanks so much for all your work on this one, I'm super excited to have it merged and launched.

**Comment by GustavoCaso** [comment]
My pleasure to be able to work, and help this great project

**Pull request closed without merging**
