### PR TITLE
Prevent Rikki bot from affecting behavior study

### PR DESCRIPTION
**Pull request by nilbus**
Related: #3447

### CODE REVIEW

**Comment by nilbus** [comment]
@kytrinyx Please deploy this when you can, and let me know if there's any users other than `rikki-` who should be excluded. Thanks! 😄

**Comment by kytrinyx** [comment]
Hey! Sorry it's taken me a bajillion days to get to this. rikki- is our only bot. 👍

**Comment by kytrinyx** [comment]
I'll be deploying in a little bit (have a couple of other PRs to review first.

**Comment by nilbus** [comment]
Thanks!

**Pull request merged**
