### PR TITLE
Add Emacs logo for elisp track.

### PR DESCRIPTION
**Pull request by canweriotnow**
Added 256px transparent PNG for Elisp track in public/img/elisp.png.

Not sure what else needs to happen for it to be associated with the exercises, trying to close out https://github.com/exercism/xelisp/issues/19 

If someone wants to point me in the direction of associating the icon, I'll add that to the PR before it's merged.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Last time this came up there was something in the CSS.

Grep pulls this up:

```
$ git grep png public/sass/
public/sass/base/components/brand.scss:  background: url('/img/e_small.png') center no-repeat;
public/sass/base/components/brand.scss:    background: url('/img/e_red_small.png') center no-repeat;
public/sass/base/components/main.scss:  background-image: url('/img/ruby.png');
public/sass/base/components/main.scss:  background-image: url('/img/javascript.png');
public/sass/base/components/main.scss:  background-image: url('/img/ecmascript.png');
public/sass/base/components/main.scss:  background-image: url('/img/elixir.png');
public/sass/base/components/main.scss:  background-image: url('/img/clojure.png');
public/sass/base/components/main.scss:  background-image: url('/img/coffeescript.png');
public/sass/base/components/main.scss:  background-image: url('/img/golang.png');
public/sass/base/components/main.scss:  background-image: url('/img/python.png');
public/sass/base/components/main.scss:  background-image: url('/img/haskell.png');
public/sass/base/components/main.scss:  background-image: url('/img/java.png');
public/sass/base/components/main.scss:  background-image: url('/img/clojure.png');
public/sass/base/components/main.scss:  background-image: url('/img/objective-c.png');
public/sass/base/components/main.scss:  background-image: url('/img/scala.png');
public/sass/base/components/main.scss:  background-image: url('/img/perl5.png');
public/sass/base/components/main.scss:  background-image: url('/img/cpp.png');
public/sass/base/components/main.scss:  background-image: url('/img/swift.png');
```

After that, my guess is as good as yours, unfortunately.

**Comment by canweriotnow** [comment]
I should be able to find it from there, thanks!

Although this does maybe point to a place to break up/refactor the scss :)

**Comment by canweriotnow** [comment]
Well, I got the css class added, no idea where to add it in the layout... I'll do some grep'ing tomorrow unless @kytrinyx or someone can point me in the right direction again :smile:

**Comment by kytrinyx** [comment]
I think the CSS class is added automatically because of the track id. I'll rebase this, regenerate the CSS (because I broke the buildpack and couldn't figure out how to fix it), and see if it works locally :)

**Comment by kytrinyx** [comment]
It works. BRING IT.

**Comment by canweriotnow** [comment]
w00t! Thanks @kytrinyx!

**Pull request merged**
