### PR TITLE
2971: Bulk archive of submission

### PR DESCRIPTION
**Pull request by aranair**
## Issue
[Bulk archive of submission](https://github.com/exercism/exercism.io/issues/2971)

## What this is
- Remove form action
- Bind listener to submit buttons and dynamically add the action back
- If it breaks
- Everything else should behave in the same way
- Also added additional specs for bulk delete

## Screenshots
 
screenshot 2016-07-22 09 34 34
screenshot 2016-07-22 09 34 24

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you so much for this! I'll get this reviewed today.

**Comment by kytrinyx** [comment]
If someone does not have javascript, will they still be able to archive and delete exercises?

**Comment by aranair** [comment]
Nope, is that a requirement? I'm not sure if that is possible if using the same form (and checkboxes) mm.

**Comment by aranair** [comment]
EDIT: Actually seems like there -are- a few options without JS. `formaction` (but drops IE9 support, is that a concern?) or passing a value via the button. I'll try out both to see if i can remove the dependency. @kytrinyx

**Comment by aranair** [comment]
Updated it with the `formaction` method. Let me know which is the preferred way :P

**Comment by kytrinyx** [comment]
> Nope, is that a requirement?

We have people using the site with screenreaders, and while screenreaders sometimes do support javascript, I would absolutely prefer to keep support available.

> Updated it with the formaction method. Let me know which is the preferred way :P

I think that's fine. IE9 is no longer supported by Microsoft, so it seems legit to drop support for that here.

**Comment by kytrinyx** [comment]
This looks good, thank you!

**Pull request merged**
