### PR TITLE
Add documentation about teams

### PR DESCRIPTION
**Pull request by aaron-suarez**
Add documentation for using teams with exercism. Where would you like me to link this new page from? app/views/application/footer/links.erb?

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @aaron-suarez!

> Where would you like me to link this new page from?

I think the footer links is a reasonable place to start.

Also, we have a section on the dashboard called "your teams", which currently doesn't show up if you don't have any. How about we always show this section, and then if you don't have any teams we show the documentation?

**Comment by aaron-suarez** [comment]
@kytrinyx I went ahead and added the documentation to the dashboard like you said. There was probably a more efficient way to do it, but I'll do some therapeutic refactoring later. Right now I'm more concerned with the large amount of whitespace to the right of the documentation. See pix below:

teams-dashboard
teams-dashboard 1

Should I extend the teams section to go all the way across?

**Comment by aaron-suarez** [comment]
And apparently I broke it.. Please let me know how to fix that.

**Comment by kytrinyx** [comment]
Nah, let's leave the whitespace. I think we're going to give the dashboard a proper think-through pretty soon.

The broken build is this:

```
The command "! git grep ' $' -- \*.rb" exited with 1.
```

That means there's trailing whitespace somewhere. Let me know if you want a hand finding it.

**Comment by aaron-suarez** [comment]
It wasn't hard to find. `grep -nr '[[:blank:]]$' .`

**Comment by kytrinyx** [comment]
OK, cool! I've looked through this and the only thing that worries me is that there's so much duplication between teams.erb and teams_small.erb. Inevitably we're going to update one and not the other. 

One thing we could do is have a shorter, generic blurb on the dashboard and then link to the /teams/about page. Or partials, I guess, but that seems like overkill for this.

**Comment by aaron-suarez** [comment]
Yeah, like I said before, I just wanted to get it up and running to see how it would look. I'm going to get rid of teams_small.erb and figure out how to just display the content we need when we need it. As long as the page looks good, I'll keep it looking like that and cut down the code.

**Comment by kytrinyx** [comment]
Sounds great!

**Comment by aaron-suarez** [comment]
I decided to run with your idea of a smaller blurb and a link. I think it looks good now, let me know what you think.

**Comment by kytrinyx** [comment]
Sweet. I'm being a bit lazy (also it's past midnight here)... do you happen to have a screenshot of the new dashboard blurb?

**Comment by aaron-suarez** [comment]
teamsblurb

**Comment by aaron-suarez** [comment]
@kytrinyx was this good? Do you need me to fix anything before you merge the PR?

**Comment by kytrinyx** [comment]
Hey! So sorry—the past month has been nuts. This looks excellent. I'll fix the conflict and get this deployed today.

Thank you so much for taking the time to work on this and experiment with the various approaches. :heart:

**Comment by kytrinyx** [comment]
Merged in f2328d0b27999d9203e9b47ebdb70944a67086de

**Comment by aaron-suarez** [comment]
Thanks Katrina, I'm glad you liked it! We'll keep working these issues with Teams.

**Pull request closed without merging**
