### PR TITLE
Make repository links consistent in `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by nisusam**

### CODE REVIEW

**Comment by Insti** [comment]
tbh, I prefer the original way where the word repository was included in the link.

**Comment by nisusam** [comment]
@Insti, Shall I update the other links where the word repository not included in link?

**Comment by Insti** [comment]
@nisusam that would be a better way to make them consistent imo :+1:

**Comment by nisusam** [comment]
@Insti PR Updated

**Comment by kytrinyx** [comment]
Thanks so much @nisusam!

**Pull request merged**
