### PR TITLE
Document that port 8000 must be used for lineman reloading

### PR DESCRIPTION
**Pull request by nilbus**
Using port 4567, I couldn't figure out why my JS wouldn't reload with lineman building things for me. Hopefully this will help others later who hit the same problem.

### CODE REVIEW

**Comment by kotp** [comment]
Can someone verify this is indeed a requirement for this specific port number?  A reference perhaps?  It feels to me that it should be configurable to match whatever rackup is set up to.

**Comment by nilbus** [comment]
It seems to be convention, documented all over [docs/setting-up-local-development.md][1], and hard-coded in the lineman config, [frontend/config/application.coffee][2].

[1]: https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md
[2]: https://github.com/exercism/exercism.io/blob/master/frontend/config/application.coffee#L18

**Comment by nilbus** [comment]
docker-compose.yml also uses 4567, consistent with everything else.

That's not to say it couldn't be changed, but the default rackup port and default puma port aren't the same.

**Comment by kytrinyx** [comment]
Thanks, @nilbus.

**Pull request merged**
