### PR TITLE
public/img/tracks: resize, crop, etc to fix #2394

### LINKED ISSUE #2394: Add exercise: Balanced parenthesis
Write a function that takes a string and returns `true` if the parentheses are balanced within the string.  Parentheses are balanced if every opening parenthesis character `(` is followed by a matching closing parenthesis character `)`.

In this form the exercise is pretty simple.  The exercise can be made more difficult by including other forms of open/closed pairs: `<` and `>`, `{` and `}`, `[` and `]` and requiring that balance means that each form must be closed without straddling another open pair.

Examples:
* `"()"` is balanced
* `"(()"` is not balanced
* `")("` is not balanced
* `"[()]"` is balanced
* `"[(])"` is not balanced
* `"Hello (world)!"` is balanced

Source: a [discussion on usenet](https://groups.google.com/forum/#!topic/comp.lang.c++/EwE1asaBjNQ)

### PR DESCRIPTION
**Pull request by catb0t**
fixes http://github.com/exercism/exercism.io/issues/2934

* VB.NET and D: give names which exactly match
	their language track slugs.
* C: buffered icon on the top and bottom because
	it looked odd.
* Nim, R, Standard ML and VB.NET: resized and re-
	-worked icons to look better.

The Groovy and SML icons are still weird and
squishy but they're as good as I can get without
training in graphic design, and they're better
than nothing.

### CODE REVIEW

**Comment by kytrinyx** [comment]
The problems with the squishiness is that the actual icon should be square, even if most of it is whitespace (I learned that the hard way). Want to change the canvas size and then crop to a square?

**Comment by catb0t** [comment]
That's what I did to get these, but the things themselves aren't *remotely* square and are elongated to where it's tricky, or they get tiny and hard to read / discern. 

I'm totally open to just dropping those icons from the page until someone has a better idea.

**Comment by kytrinyx** [comment]
Yeah, I think maybe we should just drop them until someone has a better idea. I'll open a design issue in the discussions area.

**Comment by kytrinyx** [comment]
OK, referenced from here: https://github.com/exercism/exercism.io/issues/2910

**Comment by catb0t** [comment]
Fixed.

**Comment by kytrinyx** [comment]
Excellent, thank you!

**Pull request merged**
