### PR TITLE
Reimplement Language.of to use X-API

### PR DESCRIPTION
**Pull request by karloxyz**
https://github.com/exercism/exercism.io/issues/2630

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm getting some build failures on this. Do we need to stub in some data for the integration tests?

**Comment by karloxyz** [comment]
Hmm, I didn't need to do anything special on my local machine to make the tests pass. I'll check again when I get home.

**Comment by kytrinyx** [comment]
Try turning off your wireless connection and re-running the tests. It might be talking to the API at x.exercism.io

**Comment by karloxyz** [comment]
Yup, that was the case. I'll stub them out.

**Comment by kytrinyx** [comment]
Ah, dang :) Yepp. You can do whatever you like with the PRs. I have no idea what would happen with the date if you did a `git push -f` to your branch to update the PR.

**Pull request closed without merging**
