### PR TITLE
Fixes #3020

### LINKED ISSUE #3020: Team stream: Show exercise language
When viewing all exercises in a team with multiple languages, there is no indication of which language a particular solution is in.

exercism - team stream all

There should be some way of seeing the languages of the solutions.
 
**Suggestion:** A little language track icon to the left of the problem name.

**To reproduce:** 
In a developement environment:
Assume 'amelie' and visit: http://localhost:4567/teams/slate/streams

### PR DESCRIPTION
**Pull request by sobinsunny**
added Language icon  in the left side of problem name

### CODE REVIEW

**Comment by bernardoamc** [comment]
Hi @sobinsunny thanks for the PR!

Can you edit your PR title describing what you did and add the `Fixes #3020` in the description? Could you also add a screenshot? 🙏

**Comment by Insti** [comment]
This appears to be a fix for the same issue as the earlier PR: #3072
(Please correct me if I misunderstand.)

**Comment by sobinsunny** [comment]
@Insti Yeah , Same issue . Sorry ,I didn't notice that pull request when sending this one !

**Comment by Insti** [comment]
@sobinsunny No problem. I'm going to close this request to try and avoid further confusion.

Thanks for your contribution and I hope you can find something else to help with.
Have a look through the [list of good first patches](https://github.com/exercism/exercism.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22) and see if there is anything there that inspires you, and let us know if you need any help.

**Pull request closed without merging**
