### PR TITLE
Add track mentor on user and data task for migration

### PR DESCRIPTION
**Pull request by mhelmetag**
Related to #2501 

Migrations for steps 1, 2 and 3:

>1. Create a migration that creates a new column on users called track_mentor that nothing references.
2. Create a data migration (lib/tasks/data.rake) to copy data from users.mastery to users.track_mentor
3. Deploy and run db migration and data migration.

@kytrinyx , let me know what you think and if these changes make sense for these first few steps.

### CODE REVIEW

**Comment by mhelmetag** [comment]
A test...

Migration:
```
Maxs-MBP:exercism.io max$ rake db:migrate
== 201512292315 AddTrackMentorToUser: migrating ===============================
-- add_column(:users, :track_mentor, :text)
   -> 0.0008s
== 201512292315 AddTrackMentorToUser: migrated (0.0009s) ======================

Maxs-MBP:exercism.io max$ rake data:migrate:track_mentor
```

After migration:
```
pry(main)> mastery_arr = User.all.collect { |u| u.mastery }
pry(main)> track_mentor_arr = User.all.collect { |u| u.track_mentor }
pry(main)> mastery_arr == track_mentor_arr
=> true
```

**Comment by kytrinyx** [comment]
This looks excellent, thank you!

**Comment by kytrinyx** [comment]
Aaaand deployed/migrated without a hitch.

**Comment by mhelmetag** [comment]
Suhweet!! Refactor of tests and migration to delete `mastery` column from users coming soon. Then I get to play around with some UI stuff!! :smile:

**Comment by kytrinyx** [comment]
Yay, I'm excited about that UI stuff.

**Pull request merged**
