### PR TITLE
Add bottom margin to code snippets

### PR DESCRIPTION
**Pull request by bhoover85**
This is for issue #3046 

I added a bottom margin to `.highlight` to address the spacing issues with the code snippets.

### CODE REVIEW

**Comment by Insti** [comment]
Thanks @bhoover85 
Are you able to add before and after screenshots to a comment here in the PR?

**Comment by Insti** [comment]
(I'm not a designer, but) I wonder is 35 px too big?

**Comment by bhoover85** [comment]
Hi @Insti, here's a before/after image with the 35px margin. I prefer the whitespace for readability, but I'm open to changing it to whatever the consensus is.

code_snippet_margin


Here's the 20px margin:

20px_margin

**Comment by bhoover85** [comment]
For reference, the h2 headers use a 45px margin.

**Comment by Insti** [comment]
Thanks for the screenshots @bhoover85.

I prefer the 20px version because it keeps the flow of the instructions. (I might even go lower so it matches the margin to the line of text above.)

But if the consensus turns out to be for something else I don't mind that much.

**Comment by troubalex** [comment]
Since ```<p>``` only has a margin of 10px, 35px below the code snippets might be a bit much. It works well for cases where there is a new section starting below, such as on the CLI page. On others, where the paragraph below still refers to the snippet, it breaks the context on the page. For the time being, 20px work indeed better.

Other than that: LGTM 👍

**Comment by Insti** [comment]
Looks good :+1: 

The test coverage has **not** decreased with this PR @coveralls seems to be a bit confused.

**Comment by kytrinyx** [comment]
Coveralls is a bit too touchy, for my taste.

Thanks for making the fix @bhoover85! 🎉

**Pull request merged**
