### PR TITLE
Multiple: Include link to windows installer, Adding instructions for Windows Subsystem for Linux to Setting Up Development Environment

### PR DESCRIPTION
**Pull request by Raptorian**
Closing, Adding instructions shown in another pull request, Include link will be done with another branch.

### CODE REVIEW

**Comment by Raptorian** [comment]
Well I screwed up in terms of pull requests in that I forgot to branch of to make another pull request.... Oops.

But I guess I might as well change the title and make this into multiple.

First I want to add a link to the Windows Installer for the CLI. 

Next, I want to add steps for Windows Subsystem for Linux to Setting Up Development Environment, because steps I took to get bin/setup to work are different than the steps normally provided for linux, and I thought it would be useful.

**Comment by Insti** [comment]
Please separate this into individual pull requests. :)

`git push --force` is your friend in this situation.

**Comment by Raptorian** [comment]
Will do tomorrow... I need to sleep right now. Might just be easier to close this one, create another branch and commit my changed files to that branch instead of master.

**Comment by Insti** [comment]
Yes, definitely create a branch to commit to.
You can keep the features separated on different branches.

git makes all this easy, but it can be quite confusing when you're getting started with it.

This page has some helpful information: https://yangsu.github.io/pull-request-tutorial/

**Pull request closed without merging**
