### PR TITLE
Stick public conversation in a page. Fixes #1601

### LINKED ISSUE #1601: Add public example of conversation with link from homepage
It's currently very difficult to understand what exercism is about, and how it gets used. I think that it would be helpful to have a "see an example" section on the homepage, right between the three bullet points and the "try it" section.

My first inclination is to have a (blurred?) screenshot of a real exercise/conversation, and then some text that invites people to follow a link to a separate page where an entire series of iterations + conversation is laid out.

This would not be linking to a real conversation, but it should be real code examples with actual real-life comments (perhaps edited for brevity, if necessary).

The conversation could be anonymised, if that makes the people involved more comfortable.

The biggest problem that I have with this is design/UI. I don't know what this should look like. I have a couple of suggestions, but my HTML skills are severely lacking.

@breethomas Is this something that you'd have time to work with me on?

### PR DESCRIPTION
**Pull request by kytrinyx**
This is an attempt at improving the onboarding process, specifically by making it easier to understand what exercism is about before making people log in/sign up, as well as setting the tone for the type of conversation that we're encouraging.

The conversation is real—DataWraith and I actually had these back-and-forths on his real code a few weeks ago, and he graciously agreed to share it publicly.

In order to expose this, I want to add a section to the homepage between the three bullet points and the "try it" section.

---

**setup**

You don't need the whole site (database, etc) working to work on this page.
1. Fork and clone the repository
2. Set this repository as the upstream `git remote add upstream https://github.com/exercism/exercism.io.git`
3. Fetch the upstream repository `git fetch upstream`
4. Check out the public-conversation branch: `git checkout -b upstream/public-conversation`
5. Start the server with `rackup -p 9000` (or some other port)
6. Open the conversations page at [http://localhost:9000/conversations/1](http://localhost:9000/conversations/1)

The view is in `./lib/app/views/site/conversations.haml`

We could make that Erb if that's easier for you, just let me know (this is a prototype, it's kind of crazy).

The controller action is here (but you probably won't need it) `./lib/app/routes/conversations.rb` and the underlying data is stored here in `./data/conversations`.

Don't even worry about putting the styles in some global stylesheet—all of that is a complete and utter mess. If you stick it in the page for now, that would be totally awesome. We can move it after. Or we can talk about stylesheets :)

---

I have no idea what it should look like, but ANYTHING is probably better than what I have right now. I don't know, maybe something like the conversations in iMessage where there's a color difference between the two people and it happens in two columns?

---

/cc @breethomas @courtney @bunnymatic @michaelavila

(Side note: I was going to try to make it to the Santa Monica Carbon Five Hacknight last night, but work ended up expanding into the evening hours. Any chance any of you Carbon Fivers go to that?)

### CODE REVIEW

**Comment by hpurmann** [comment]
I'm [refering to this conversation in an older blog post](http://hpurmann.com/2015/02/25/exercism/). Is this conversation still online somewhere?

**Comment by kytrinyx** [comment]
@hpurmann the conversation isn't up anywhere, but it's in the git history: https://github.com/exercism/exercism.io/commits/64a8cdca65df9618327ed6c062afb87c80d7097e/data/conversations/1.json

(the formatting isn't awesome, though :/)

**Comment by hpurmann** [comment]
Thanks! That's unfortunate. I removed the paragraph.

**Comment by kytrinyx** [comment]
Ok. Sorry about that!

**Pull request merged**
