### PR TITLE
WIP: Add per_page to TeamStream 

### PR DESCRIPTION
**Pull request by jendiamond**
We finally got the page to paginate.

We passed `per_page=2` in the url to test this as per @kytrinyx 's suggestion,   
but we also had to change something on the TeamStream model to make that change take effect.

```ruby
class TeamStream
  attr_reader :team, :viewer_id, :page, :track_id, :user_id, :username, :slug
  attr_accessor :per_page

  def initialize(team, viewer_id, page=1, per_page=50)
    @team = team
    @viewer_id = viewer_id
    @page = page.to_i
    @per_page = per_page.to_i
  end
```
`per_page` is a new parameter. It was previously always set to 50. Now it can be set when you initialize the TeamStream. 

We also changed the team routes to pass in the `per_page` URL param to the initializer.

@chrimifi @lenkli67 @curvgrl5000 @davdkm @Kwon11 @lisamarie616

This is a continuation of our previous PR  https://github.com/exercism/exercism.io/pull/3005 
As per your request we will leave this one open and continue to push here.

### CODE REVIEW

**Comment by Insti** [comment]
I have many issues/comments with this PR, but I'll hold off on commenting for now because I know this is more 'in progress' than a lot of other PRs.

**Comment by jendiamond** [comment]
I see that the PR includes all the update since we last pushed. We are trying to figure out the best way to pull the changes, and rebase the branch. Apparently we did it wrong this time.

**Comment by Insti** [comment]
I think you needed to "rebase" rather than "pull" or "merge"
Try doing:
```
git rebase master
git push --force origin team-pagination
```
And see if that fixes it.

**Comment by jendiamond** [comment]
These are the steps that we did. Do you see where we went wrong?

$ git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 231 commits.
  (use "git push" to publish your local commits)

$ git pull upstream masterFrom https://github.com/exercism/exercism.io
 * branch            master     -> FETCH_HEAD
Already up-to-date.

$ git checkout team-pagination 
Switched to branch 'team-pagination'

$ git status
On branch team-pagination
nothing to commit, working directory clean

$ git rebase master
Current branch team-pagination is up to date.

$ git push origin team-pagination 
To git@github.com:jendiamond/exercism.io.git
 ! [rejected]        team-pagination -> team-pagination (non-fast-forward)
error: failed to push some refs to 'git@github.com:jendiamond/exercism.io.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

$ git push origin team-pagination -f
Counting objects: 1007, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (438/438), done.
Writing objects: 100% (740/740), 170.42 KiB | 0 bytes/s, done.
Total 740 (delta 542), reused 396 (delta 289)
remote: Resolving deltas: 100% (542/542), completed with 130 local objects.
To git@github.com:jendiamond/exercism.io.git
 + e857f70...faa36ad team-pagination -> team-pagination (forced update)

$ git rebase master
Current branch team-pagination is up to date.

**Comment by Insti** [comment]
You've not rebased your local master on the upstream master.

Try:
```
git checkout master
git fetch upstream
git rebase upstream master
git checkout team-pagination 
git rebase master 
git push origin team-pagination --force
```

**Comment by jendiamond** [comment]
## Seem to be making progress but I often run into this error while rebasing which is where I am now.
Do I just say `$ git rebase --skip` ?
```
*git rebase --continue
Applying: Remove ExercismWeb::Presenters::Assignment and corresponding files
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

---

## Here is what happened following your directions

```
$ git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 231 commits.
  (use "git push" to publish your local commits)

$ git fetch upstream
remote: Counting objects: 86, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 86 (delta 51), reused 39 (delta 39), pack-reused 14
Unpacking objects: 100% (86/86), done.
From https://github.com/exercism/exercism.io
 * [new branch]      Gitter_For_Tracks_With_Rooms -> upstream/Gitter_For_Tracks_With_Rooms
   8ccf8fd..0de777d  master     -> upstream/master
 * [new branch]      travis     -> upstream/travis
 * [new branch]      xlisp-highlighting -> upstream/xlisp-highlighting

$ git rebase upstream master
fatal: Needed a single revision
invalid upstream upstream

$ rvm list rubies
rvm rubies
   ruby-2.2.1 [ x86_64 ]
=> ruby-2.2.2 [ x86_64 ]
 *  ruby-2.3.0 [ x86_64 ]

$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: Remove unreachable instance methods on ExercismWeb::Presenters::Profile
Using index info to reconstruct a base tree...
M	app/presenters/profile.rb
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Remove ExercismWeb::Presenters::Sharing
Using index info to reconstruct a base tree...
M	app/presenters.rb
A	app/presenters/sharing.rb
M	app/routes/submissions.rb
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Remove unreachable code from ExercismWeb::Helpers::FuzzyTime
Using index info to reconstruct a base tree...
M	app/helpers/fuzzy_time.rb
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Remove LanguageTrack and corresponding code
Using index info to reconstruct a base tree...
M	lib/exercism.rb
A	lib/exercism/language_track.rb
M	test/app_test_helper.rb
A	test/exercism/language_track_test.rb
A	test/fixtures/approvals/tracks.json
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Remove unused instance method AttemptTest#python_two
Using index info to reconstruct a base tree...
M	test/exercism/use_cases/attempt_test.rb
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Remove ExercismWeb::Presenters::Assignment and corresponding files
Using index info to reconstruct a base tree...
M	app/presenters.rb
A	app/presenters/assignment.rb
A	test/app/presenters/assignment_test.rb
A	test/fixtures/assignments_multiple_files.json
Falling back to patching base and 3-way merge...
Auto-merging app/presenters.rb
CONFLICT (content): Merge conflict in app/presenters.rb
Failed to merge in the changes.
Patch failed at 0006 Remove ExercismWeb::Presenters::Assignment and corresponding files
The copy of the patch that failed is found in:
   /vagrant/exercism.io/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

$ git checkout team-pagination 
app/presenters.rb: needs merge
error: you need to resolve your current index first

$ git add app/presenters.rb

$ git rebase --continue
Applying: Remove ExercismWeb::Presenters::Assignment and corresponding files
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".


$ git commit -m 'app/presenters.rb'
rebase in progress; onto 0de777d
You are currently rebasing branch 'master' on '0de777d'.

nothing to commit, working directory clean

$ git rebase --continue
Applying: Remove ExercismWeb::Presenters::Assignment and corresponding files
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

---

### Changed this:
```
module ExercismWeb
  module Presenters
    {
<<<<<<< HEAD
=======
      Languages: 'languages',
>>>>>>> Remove ExercismWeb::Presenters::Assignment and corresponding files
      Inbox: 'inbox',
      Tracks: 'tracks',
      Setup: 'setup',
      Dashboard: 'dashboard',
      Profile: 'profile',
    }.each do |name, file|
      autoload name, Exercism.relative_to_root('app', 'presenters', file)
    end
  end
end
```

### To this:
```
module ExercismWeb
  module Presenters
    {
      Inbox: 'inbox',
      Tracks: 'tracks',
      Setup: 'setup',
      Dashboard: 'dashboard',
      Profile: 'profile',
    }.each do |name, file|
      autoload name, Exercism.relative_to_root('app', 'presenters', file)
    end
  end
end
```

---

```
$ git add app/presenters.rb

$ git rebase --continue
Applying: Remove ExercismWeb::Presenters::Assignment and corresponding files
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by Insti** [comment]
The 3rd step of my instructions was missing a slash character, it should have been:
```
git rebase upstream/master
```
But you seem to have worked that out :+1:

**Comment by Insti** [comment]
When you get
```
No changes - did you forget to use 'git add'?
```
You can usually do `git rebase --skip`

**Comment by Insti** [comment]
It looks like this is not going to be simple.
Another thing to try is to try starting over and `cherry-pick`ing just the relevant commits:
```
git checkout master
git branch -m team-pagination team-pagination-mess
git checkout -b team-pagination
git cherry-pick eb6c6fe..faa36ad
git push origin team-pagination --force
```

**Pull request closed without merging**
