### PR TITLE
Docs and foundations of new client

### PR DESCRIPTION
**Pull request by mtakac**
Incomplete and bit messy docs for new client. Anyway still should make many things discussed in #2296 much clearer.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yeah, this makes a lot of sense. Do you want to leave the PR open as you put together the skeleton of the client stuff?

**Comment by mtakac** [comment]
@kytrinyx sure, I can push the skeleton here.

**Comment by mtakac** [comment]
BTW I added [WIP] to the PR title to flag it as Work in Progress and not ready to merge.

**Comment by kytrinyx** [comment]
Good call in the [WIP] flag. Thanks!

**Comment by mtakac** [comment]
Ok, this can be merged. 

I finished basic setup & created an example component to illustrate working with modules and styles, templates and scripts inside of them. There are still lots of things we can improve but this should be good enough for the beginning. Now we need to come up with API endpoints...

Oh and sorry for large commit - I should have probably split it.

**Comment by kytrinyx** [comment]
No, I think that it's fine to do it in one large commit for something like this. And thank you!

**Comment by mtakac** [comment]
@kytrinyx You're welcome. I was thinking maybe I can open some smaller issues concerning front end so it's easier to track progress and for others to contribute. For example one issue could deal with API endpoints we will need, another one with changes to deployment, yet another with rewriting pieces of old front end into the new one.

**Comment by mtakac** [comment]
It would also help me to keep a track of what's done and what still needs to be addressed.

**Comment by kytrinyx** [comment]
Yeah, smaller issues could work, or medium-sized with checkboxes for related tasks. Whatever will help this process!

**Pull request merged**
