### PR TITLE
shows documentation for upcoming and planned tracks

### PR DESCRIPTION
**Pull request by ramyaravindranath**

### CODE REVIEW

**Comment by ramyaravindranath** [comment]
@kytrinyx This is the PR for https://github.com/exercism/exercism.io/issues/3094.

**Comment by catb0t** [comment]
Hooray! :D

**Comment by kytrinyx** [comment]
Thank you @ramyaravindranath!

I would like the "help launch the track" to be the first tab rather than the second-to-last, and I'd like it to be active by default.

**Comment by ramyaravindranath** [comment]
@kytrinyx This is ready for the review

**Comment by kytrinyx** [comment]
This looks great, thank you!

**Comment by kytrinyx** [comment]
:tada: :heart: :sparkles:

**Pull request merged**
