### PR TITLE
Revert "Properly handle tokens that span more than one line"

### PR DESCRIPTION
**Pull request by Insti**
This reverts commit 184b7dc3fd774b0958b28a8232bb5abfcd4f5af4.

This PR created an issue where the number of line numbers for solutions was 1 less than the number of lines in the solution. This also caused rendering issues on the solutions page as the line numbers no longer lined up with the code.

### CODE REVIEW

**Comment by Insti** [comment]
See also, Issue:  #3050
Pull Request: #3048

**Comment by Insti** [comment]
CI :x: is due to code coverage decrease. This is OK, and expected in a revert.

**Comment by kytrinyx** [comment]
Let's do this.

**Comment by kytrinyx** [comment]
I'll deploy.

**Comment by Insti** [comment]
Great. @k3rni has been working on a new branch that fixes all the problems and makes it all simpler, so expect a PR for that sometime soon.

**Pull request merged**
