### PR TITLE
Displays both file name and contents through submission hash

### PR DESCRIPTION
**Pull request by LNA**

### CODE REVIEW

**Comment by kytrinyx** [comment]
:sparkles: Sweet! 

Do you have the seed data working locally? If so, would you take a screenshot of one of the code pages?

For example, in the "Assume" menu, find someone with status "completed", and then select an exercise under "current exercises".

**Comment by LNA** [comment]
Whoopsie!

I pryed in to see what the data structures would look like once the new way its implemented, and used that as my guide, which didn't feel quite right.  I wasn't sure what to do about the seed data; should I send a pull request to the seed repo?  Change it locally?  What do you suggest?

**Comment by kytrinyx** [comment]
Oh, sorry - I wasn't clear. With respect to the seed data, I just meant: were you able to run `rake seed` and get some example problems and users?

Now that you mention it, though, I need to fix the seed data to have the `solution` hash. I'll do that this morning and let you know when it's done.

Meanwhile, if you run `rake data:migrate:solutions` then you should be able to get the proper data structures.

**Comment by kytrinyx** [comment]
OK, I've fixed the seed data.

You can reset the seeds with:

```
rake db:reset db:migrate db:seeds:fetch db:seed
```

**Comment by LNA** [comment]
Okay, I've reset the seed data. Its telling me that I need to do two things:

1. From what I can tell there is a bug with the markdown that's showing up at `/submissions/abunchofnumbers` on each feedback.  I need to be passing in a language here `/lib/app/helpers/markdown.rb` .  The language is set to nil if nothing is passes, so it won't blow up, but it sure isn't pretty! 

2. Figure out why I can't see any code when I go to `http://localhost:4567/code/ruby/leap/random`.  Even when I assume completed user, I get back 'You'll have access to that page when you complete leap in ruby'.  So I need to do some more digging there.

**Comment by kytrinyx** [comment]
For (2) I think it depends on the user that you assume the identify for:

Since the users are generated randomly, and they complete random exercises, it's not going to be in order. If you go to their account page, then there's going to be a list of completed exercises, and you should be able to click on one of those... and finally get to the random page.

**Comment by LNA** [comment]
Hi ! I've got it working, but when I run the tests I get this error: https://gist.github.com/LNA/57bf0d6f91414e608996
Any clues as to how I can fix it?

**Comment by kytrinyx** [comment]
This looks great, thank you! :heart: :heart: :heart:

**Comment by LNA** [comment]
You're welcome! What can I help with next?

**Comment by kytrinyx** [comment]
I'll go back and figure out the next step over in https://github.com/exercism/exercism.io/issues/1165

**Pull request merged**
