### PR TITLE
Reimplement language page using new x-api v3 endpoints

### PR DESCRIPTION
**Pull request by kytrinyx**
This will let us get rid of the (quite horrid) help.exercism.io site.

- reimplements the `/languages/:track_id` page
- simplifies the erb template, no partials
- gets the data from the new x-api v3 endpoints
- enhances that data a bit so that we can encourage people to contribute improvements
- adds the documentation that currently lives in help.exercism.io

**TODO**

- [x] add the "resources" documentation to the /languages/:track_id page
- [x] add the "learning" documentation to the /languages/:track_id page
- [x] handle org-mode docs - https://github.com/exercism/x-api/issues/79
- [x] handle docs images from x-api - https://github.com/exercism/x-api/pull/78
- [x] update image references in language-specific docs/*
    - [x] coffeescript
    - [x] csharp
    - [x] javascript
    - [x] python
    - [x] elisp
    - [x] fsharp
- [x] c
- [x] clojure
- [x] coffeescript
- [x] cpp
- [x] csharp
- [x] ecmascript
- [x] elisp
- [x] elixir
- [x] elm
- [x] erlang
- [x] fsharp
- [x] go
- [x] haskell
- [x] java
- [x] javascript
- [x] lfe
- [x] lisp
- [x] lua
- [x] objective-c
- [x] ocaml
- [x] perl5
- [x] php
- [x] plsql
- [x] python
- [x] r
- [x] racket
- [x] ruby
- [x] rust
- [x] scala
- [x] scheme
- [x] swift

### CODE REVIEW

**Comment by kytrinyx** [comment]
@GustavoCaso Here's what I've been working on today.

The most important pieces to notice are:

- I tackled a single action in a single route.
- I added a new directory `x/` at the root level of the repository, where I am rewriting code independently of the mess in `lib/exercism/*`
- There's a new `Xapi` client in `x/xapi.rb`, which is used in `x/track.rb`

We're going to have to go through all of the "how to get started in X" pages in https://github.com/exercism/docs/tree/master/app/pages/languages and extract the various documentation pieces to the language-specific repositories (`docs/INSTALLATION.md` and `docs/TESTS.md`. Everything else goes into `docs/RESOURCES.md`).

I'm going to get started on that tomorrow.

**Comment by GustavoCaso** [comment]
@kytrinyx Is looking great very clean. So I can help you by adding different languages  and documentation?

**Comment by kytrinyx** [comment]
That would be awesome! Want to start at the bottom and work your way up? I'll start at the top and work my way down.

**Comment by GustavoCaso** [comment]
@kytrinyx Sure sound awesome

**Comment by GustavoCaso** [comment]
@kytrinyx Ok as soon I get home I will get remove that code.
Do you want me implement more endpoints as well the tests ?

**Comment by GustavoCaso** [comment]
@kytrinyx Just to be clear because from the description is not really clear to me you want me to move from the https://github.com/exercism/docs/tree/master/app/pages/languages repo to the exercisim.io repository in the folder `docs/:languages/INSTALLATION.md`, `docs/:languages/TESTS.md` and `docs/:languages/RESOURCES.md`.

Am I right ?

**Comment by kytrinyx** [comment]
Yes, take the getting-started-with-X.md file and split it into three files: `INSTALLATION.md` for getting the language set up on your local machine, `TESTS.md` for how to run the tests or do anything else about solving the problem, and `RESOURCES.md` for anything else that might be there.

Some of the repositories have old (probably outdated) files called `HELLO.md` and `WORKFLOW.md` and `TOOLS.md` which should all be removed.

If there's an `ABOUT.md` leave it, we're hoping to get a nice intro to each of the languages eventually.

**Comment by GustavoCaso** [comment]
But divided by folders by language ??

**Comment by kytrinyx** [comment]
The new files should go into the language's repository. So the content from `getting-started-with-ruby.md` would go into https://github.com/exercism/xruby in a directory called `docs/`. Sorry--I should have said that up front!

**Comment by GustavoCaso** [comment]
Ok ok I was getting frustrated, trying to make it work adding the folder in `x/docs/elixir/TESTS.md`
Ok so I will do it in each repo language

**Comment by kytrinyx** [comment]
Oh, no. I'm so sorry!

**Pull request merged**
