### PR TITLE
Added documentation for --dir

### PR DESCRIPTION
**Pull request by blueelvis**
This is regarding Issue #3045 

I have added further documentation regarding the `exercism configure --dir` command. Please let me know if there are any corrections required :)

Also, what is the difference between \`\`\`bash\`\`\` and \`\`\`plain\`\`\`?

### CODE REVIEW

**Comment by bernardoamc** [comment]
> Also, what is the difference between ```bash``` and ```plain```?

It's the way the text inside your code block will be [highlighted](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting). 

> I have added further documentation regarding the exercism configure --dir command. Please let me know if there are any corrections required :)

Looks good to me! Thanks for the PR! :)

**Comment by blueelvis** [comment]
@bernardoamc - But, I don't see anything like this on the website. I mean the highlight is not visible on the exercism.io website. Is this only for Github?

**Comment by bernardoamc** [comment]
> I mean the highlight is not visible on the exercism.io website. Is this only for Github?

That is a good question... I don't know the answer for now. 😅

**Comment by blueelvis** [comment]
@bernardoamc - No problem :) .

**Comment by kytrinyx** [comment]
> I mean the highlight is not visible on the exercism.io website. Is this only for Github?

I don't know if rouge handles github flavored markdown ("fenceposts"?). I guess maybe it doesn't but I haven't investigated this at all.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by blueelvis** [comment]
@kytrinyx - Check out this link - https://github.com/blueelvis/exercism.io/blob/d3d1d0119f30369e113a744d6e61950e229c0ba8/x/docs/md/help/executable.md

The highlighting doesn't work in Github as well. And you are welcome :)

**Comment by Insti** [comment]
That looks fine to me @blueelvis 
What are you expecting it to look like?
`bash` is bash shell highlighting: 

```bash
#!/bin/bash
if["1"==$1];do
  echo $ENV
fi
```

`plain` isn't a type so it defaults to no formatting:

```plain
#!/bin/bash
if["1"==$1];do
  echo $ENV
fi
```
The snippets in that example have no 'interesting' tokens in them so you won't see anything highlighted.

**Comment by blueelvis** [comment]
@insti - Thanks a lot! That explains everything :)

**Pull request merged**
