### PR TITLE
Code quality

### PR DESCRIPTION
**Pull request by mrfoto**
I've added rubocop and started work on making the code "pretty". Feel free to comment/guide me what kind of style you'd like to follow.

BTW The first 3 commits could be cherry-picked and applied if you don't want to add rubocop, since they're sorta unrelated. I first wanted to fix Codeclimate's score but the Fs seem impossible to fix :grin:

### CODE REVIEW

**Comment by kytrinyx** [comment]
Hey :) Yeah, the code quality has not exactly been a priority. This has all been an experiment since the beginning. The way that I have improved quality up until now has been to extract bits of functionality into other places (like the x-api).

I think it's fine to add rubocop. We could use the style rules from https://github.com/exercism/x-api as a starting point.

I'll look through this tomorrow.

**Comment by kytrinyx** [comment]
Would you add the rubocop rules and violations as a separate PR with the addition of the config from x-api, please?

https://github.com/exercism/x-api/blob/master/.rubocop.yml

It would be much easier to assess the PRs if the new rubocop rules + the list of violations to ignore were in one PR and then a number of sequential PRs that fixed one thing at a time (e.g. the documentation fixes are one kind of fix, fixing rubocop style violations are a different kind of fix) were submitted separately.

**Comment by mrfoto** [comment]
I removed rubocop from here and moved it to #2379

**Comment by kytrinyx** [comment]
Thanks! I've merged the documentation part in fa6aeea14b591efa0b6ec4f31b7f65b05013273b and the refactoring in 5ca284bbc44f3a7d250b05aa4aaba734076df89b

**Pull request closed without merging**
