### PR TITLE
Bump Rouge version and use Ruby for Crystal syntax

### LINKED ISSUE #2988: [crystal; lfe; others?] Syntax-Highlighting
Currently there is no syntax highlighting in the tracks `xcrystal` and `xlfe`, maybe other tracks are lacking highlighting as well.

Crystal as a Ruby-inspired language, which even does borrow API-documentation from Ruby should be safe to be highlighted by the Ruby-highlighter until we get something more appropriate. But I can tell so far, that I have not come to any problems using emacs `ruby-mode` to edit my crystal stuff.

LFE should be safely highlightable by the same highlighter that powers `xemacs` or `xclojure` or `xracket` or any other lispy/schemey track. Personally I used `lisp-mode` for the first couple of exercises until I installed the more appropriate `lfe-mode`. I think that a lispy highlighter would be the best, since there are some differences in lisps and schemes way to define functions. Lisp uses the funtions name as first argument to the `defun`-macro followed by the list of arguments, while scheme uses a list which first element is the name of the function and the tail lists the arguments.

@exercism/track-maintainers if your track also does not have proper syntax highilghting but are not mentioned so far, please rise your voice, I will maintain a progresslist in this post.

- [ ] xcrystal (#2997)
- [ ] xlfe
- [ ] xfsharp (#2997)
- [ ] xlisp

### PR DESCRIPTION
**Pull request by mhelmetag**
Hi! Back again with a cleaner PR.

Partially fixes #2988

Bumps Rouge version to 2.0.5 and uses ruby highlighting for crystal.

Crystal without:
crystal_without

Crystal with:
crystal_with

F# without:
fsharp_without

F# with:
fsharp_with

Pretty colors 🌈

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Awesome!

**Comment by Insti** [comment]
Looks good.
Were there any issues with the rouge upgrade?
Have you had a look at some of the other languages to check for obvious regressions?

**Comment by mhelmetag** [comment]
@Insti , not that I can tell... I checked F#, Crystal, Ruby, Swift, C++, Rust and Java so far (the test suites and a few exercises that are loaded in the dev db).

**Comment by Insti** [comment]
Minor thing: The 'Rouge' syntax highlighter is spelled 'Rouge' rather than 'rogue'
(It's misspelled in the title and in the first post)

**Comment by mhelmetag** [comment]
Hahaha I don't know why I keep doing that...

**Comment by kytrinyx** [comment]
Excellent, thanks so much!

**Comment by ErikSchierboom** [comment]
I can confirm that F# syntax highlighting now works:

image

Thanks @mhelmetag !

**Pull request merged**
