### PR TITLE
Fix drop mastery from user migration

### PR DESCRIPTION
**Pull request by mhelmetag**
Related to #2501 

This should fix the migration and actually drop `mastery` from `users`.

Before Migration:
screen shot 2016-01-14 at 10 32 49 pm

After Migration
screen shot 2016-01-14 at 10 32 31 pm

Running migration and tests:
screen shot 2016-01-14 at 10 32 57 pm

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks!

**Comment by mhelmetag** [comment]
Yep! Sorry about that!

**Comment by kytrinyx** [comment]
I'll be regenerating seed data today--just extracting some data for the markov chain generator first.

**Comment by mhelmetag** [comment]
Awesome!!

**Pull request merged**
