### PR TITLE
Uses solution field to display code

### PR DESCRIPTION
**Pull request by LNA**

### CODE REVIEW

**Comment by LNA** [comment]
Sounds good! 

Where do you think the file name should be displayed?
Also, what do you mean by "loop through the solutions hash?"

**Comment by kytrinyx** [comment]
> Where do you think the file name should be displayed?

How about above the related code?

> Also, what do you mean by "loop through the solutions hash?"

I was thinking loop through each key and value so that if there are multiple, we don't only see the first one:

```ruby
{"file1.rb" => "# code 1", "file2.rb" => "# code 2"}.each do |filename, code|
  # display the filename and the code
end
```

**Comment by LNA** [comment]
Okay!

I'm finally back in the swing of things after the holidays :) I'll be working on exercism this afternoon, for Waza.

**Comment by kytrinyx** [comment]
w00t :) Let me know if you need anything.

**Pull request merged**
