### PR TITLE
Update Compass instructions for compiling the csss to production

### PR DESCRIPTION
**Pull request by GustavoCaso**
@kytrinyx 

I have notice that the documentation for compiling the css to production is outdated.

for references [compass-production](http://compass-style.org/help/tutorials/production-css/)

### CODE REVIEW

**Comment by bernardoamc** [comment]
Nice catch. 👍

**Comment by troubalex** [comment]
Thank you! I kept thinking I was doing something wrong.

**Comment by GustavoCaso** [comment]
Your welcome @troubalex

**Comment by GustavoCaso** [comment]
@kytrinyx do you want me to include anything else in the documentation ?

**Comment by kytrinyx** [comment]
This looks great, thank you @GustavoCaso

**Pull request merged**
