### PR TITLE
Replace ZeroClipboard with clipboard.js

### LINKED ISSUE #2602: The 'copy' button not working?
image

I'm assuming this button is to copy the code, but it does nothing for me - doesn't give me a pointer cursor and does nothing when I click on it.

Also looks like it's using flash which seems strange on a website that doesn't have any other flash. There are other friendlier ways to enable this using javascript (which is native to _every_ browser) instead of flash.

### PR DESCRIPTION
**Pull request by krishandley**
Fixes #2602 and #2419

Is public/js/app.js supposed to be in version control?

I wouldn't normally have minified files locally so I put the unminified version of clipboard.js in, but if you are deploying that file I can change it to the minified version.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Cool, thanks!

The build is failing with:

```
The command "( cd frontend && npm install && lineman spec-ci )" exited with 3.
```

It might just mean that an outdated test needs to be deleted or something.

> Is public/js/app.js supposed to be in version control?

Yeah, kind of. The heroku buildpack for minimizing the js and compiling the css broke, and since I don't have frontend skills I just committed the resulting file and moved on.

If you know enough frontend to help out with this, I'd love to figure out what to do to make it right.

**Comment by krishandley** [comment]
Updated to the minified version.

I had never even heard of lineman until this morning! And I've never done anything with a buildpack other than use someone else's, so I make no promises :stuck_out_tongue:

**Comment by kytrinyx** [comment]
Hah. Yeah--I'm going to ditch lineman as soon as I can get out from under the pile of other things I need to do. It was built to solve a particular kind of problem, and Exercism really isn't that problem.

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
