### PR TITLE
Provide access to solutions after submitting

### PR DESCRIPTION
**Pull request by kytrinyx**
Rather than making people mark an exercise as 'done', let them see and comment on
other people's exercises as soon as they've submitted one solution to the problem
themselves.

Addresses #2510

### CODE REVIEW

**Comment by sguermond** [comment]
@kytrinyx Yes but I am not sure how to!

**Comment by kytrinyx** [comment]
Here's how I usually do it:

```
git fetch upstream refs/pull/2512/head
git checkout -b kytrinyx/unlock-access FETCH_HEAD
```

Then restart the browser and click around.

**Comment by sguermond** [comment]
I think this is going to be great paired with a better way of finding other people.

**Comment by kytrinyx** [comment]
Yeah, me too. I'm really excited about some of the simplifications I think we can make now.

**Comment by mixolidia** [comment]
It looks great.

**Comment by kytrinyx** [comment]
Ok, cool. Merging!

**Pull request merged**
