### PR TITLE
Add frontend build tasks and lineman install to bin/setup

### LINKED ISSUE #3145: Fix bin/setup to compile CSS and JS
Since we merged the pull request that lets us stop committing the compiled assets, the bin/setup (probably) needs to install npm and lineman, and run compass compile per the contributing guide: https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#frontend-development-setup

```
$ bundle exec compass compile -e production --force
$ npm install -g lineman
$ npm install
$ cd frontend && lineman build
```

I have not tested running setup from scratch.

### PR DESCRIPTION
**Pull request by mhelmetag**
I think this would get close or fix #3145 but... I keep getting hung up on jshint warnings when running `npm install`. I seem to get this normally (I usually just `--force` like it tells me too).

### CODE REVIEW

**Comment by Insti** [comment]
I'm not a fan of things that force global installs on me. 
If I want it installed globally I'll do it myself.

**Comment by tejasbubane** [comment]
@mhelmetag we also need to add `compass compile` and `lineman build` steps as Katrina has mentioned in the issue.

**Comment by mhelmetag** [comment]
@Insti , lineman has to be installed globally to work though... (one of the downsides to lineman)

**Comment by kytrinyx** [comment]
Ideally we'll get rid of lineman (soon?).

@olivierlacan also made some fixes to `bin/setup`. Want to arm-wrestle for which PR to accept first? Or discuss which implementations or bits and pieces you all like better?

See
- https://github.com/exercism/exercism.io/pull/3176
- https://github.com/exercism/exercism.io/pull/3175

**Comment by olivierlacan** [comment]
@tejasbubane Compass compile is in #3176. 

@kytrinyx No arm wrestling for me, I have very sensitive hands. 😸

**Comment by tejasbubane** [comment]
> shouldn't this run all of those automatically on npm install? Seems like that happened... But I'm probably wrong 😆

@mhelmetag Yeah, the `postinstall` script should do `lineman build` and `compass compile` as well.

**Comment by mhelmetag** [comment]
@tejasbubane , so... if I understand correctly we only really need to `npm install` and it'll take care of the `lineman` and `compass` stuff...

@olivierlacan , since it looks like only one line needs to be added (and maybe a check for a global install of lineman), I'm totally fine to close my PR out.

**Comment by mhelmetag** [comment]
@Insti , removed the forced global install of lineman in favor of an error message.

**Comment by kytrinyx** [comment]
Thanks, everyone!

**Pull request merged**
