### PR TITLE
Locks the Rubocop version

### PR DESCRIPTION
**Pull request by kotp**
re: exercism/exercism.io#2846

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is failing the build. Did you run `bundle check` after making this change?

**Comment by kotp** [comment]
I did not, but I did do a bundle install.  Having run bundle check now, it is still reporting 'good'.  I can look at this deeper in about an hour or so.

**Comment by kytrinyx** [comment]
Weird, OK, thanks!

**Comment by kotp** [comment]
I missed adding in the Gemfile.lock, this should fix it.  The x-api does not track the `Gemfile.lock` I thought this also did not.

**Pull request merged**
