### PR TITLE
[Finishes #2856] - Modify dashboard for users with no submissions

### PR DESCRIPTION
**Pull request by cshutchinson**
Modify dashboard for users with no submissions.

### CODE REVIEW

**Comment by kytrinyx** [comment]
(adding note so that this issue links to the other one) - See discussion in #2856

**Comment by kytrinyx** [comment]
Would you mind posting a screenshot of what this will look like?

**Comment by cshutchinson** [comment]
Here is the screenshot
screen shot 2016-05-10 at 7 30 28 pm

**Comment by kytrinyx** [comment]
Nice, thanks!

**Pull request merged**
