### PR TITLE
Kaoru speed up nitpicks endpoint 2208

### PR DESCRIPTION
**Pull request by KaoruDev**
@kytrinyx hey this is my first PR and this branch is still WIP i really wanna test it further and get some benchmarks around it to see if it **really** is faster. I just wanted to get this on your radar to see if I'm on the right track. Thanks!

oh this attempts to address #2208

### CODE REVIEW

**Comment by kytrinyx** [comment]
This looks great, thank you so much for tackling this.

The tests are still failing--it looks like a `NoMethodError` in some places.

When the test suite passes, would you mind rebasing onto master and squashing the commits? I'd love to get this pulled in.

**Comment by KaoruDev** [comment]
hey @kytrinyx i'm trying to fix the test but need some clarification on the behavior of `Cohort`

Specifically: https://github.com/exercism/exercism.io/blob/master/test/exercism/cohort_test.rb#L42

Why is Eve not involved?

**Comment by KaoruDev** [comment]
nm i think I understand, Eve has not submitted anything.

**Comment by KaoruDev** [comment]
@kytrinyx ok i think this is ready now =)

**Comment by kytrinyx** [comment]
>  i'm trying to fix the test but need some clarification on the behaviour of Cohort

Yeah, you figured it out. Eve is in the team, but hasn't submitted that exercise yet, and shouldn't have access to it.

**Comment by kytrinyx** [comment]
Thank you so much for working on this!

**Pull request merged**
