### PR TITLE
F/x api v3 and readme

### PR DESCRIPTION
**Pull request by ben-biddington**
Build status

I realise now this doesn't follow [your pattern](https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/test/x/track_test.rb), so feel free to discard. (I am not a huge fan of faking the internet.)

Here I have treated [`X::Exercise::Readme.find(track_id, slug)`](https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/x/readme.rb) as an adapter, and as such proved it works with a [integration checks](http://www.natpryce.com/articles/000772.html). 

https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/test/integration/x/exercise_test.rb

* [`X::Exercise::Readme.find(track_id, slug)`](https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/x/readme.rb) is based on [`X::Track`](https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/x/track.rb) and your [suggestion](https://github.com/exercism/exercism.io/issues/2631). Tried metaprogramming those but in the end they're different enough.
* There [are some error propagation defects with the api itself](https://github.com/ben-biddington/exercism.io/blob/f/x-api-v3-and-readme/test/integration/x/exercise_test.rb#L27).
* Really don't know [what travis is on about](https://travis-ci.org/ben-biddington/exercism.io/builds/94347992). Any ideas?

### CODE REVIEW

**Comment by ben-biddington** [comment]
Likely duplicate of https://github.com/exercism/exercism.io/pull/2646

**Comment by kytrinyx** [comment]
@ben-biddington sorry about the duplicate work! There's been a lot going on and I missed that there was no claim on the readme issue :/

I've not settled on a good pattern for the integration tests. We can't call out across the internet since CI runs in a completely isolated environment. I've been back and forth on VCR vs just stubbing in fixtures vs just mocking that the right call gets made. I'm leaning towards the last one at the moment, though the codebase is all over the place.

**Comment by ben-biddington** [comment]
Yeah I am going to pick up something else -- you *can* do those calls though, they're working [here](https://travis-ci.org/ben-biddington/exercism.io/builds/94347992).

**Comment by kytrinyx** [comment]
Ah, I didn't realize that. Thanks.

**Pull request closed without merging**
