### PR TITLE
Trending

### PR DESCRIPTION
**Pull request by bmulvihill**
Base on Issue https://github.com/exercism/exercism.io/issues/2325
I have been playing around with a trending feature on the Dashboard to try and encourage more exploration.  I am not sure if this is something that would help, but figured I would open this PR to open the discussion, see what people thought.  

This could definitely be expanded upon/altered to provide different types of data.  I also reorganized the dashboard slightly to use columns.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I am sorry I haven't had a chance to look at this yet. I may need to wait until the weekend to get on top of everything.

**Comment by kytrinyx** [comment]
I wanted to apologize for still not getting to this. The past few weeks have been pretty rough, I'm going to need one more week to get on top of things.

One thing that I noticed when trying it out locally (maybe because my data is very old), is that if there's nothing trending the "Currently trending" is still showing.

**Comment by bmulvihill** [comment]
No worries! yeah I am not hiding the main header at the moment if there is nothing found.  I can make an update to do that.

**Comment by kytrinyx** [comment]
That would be great, thanks!

**Comment by kytrinyx** [comment]
Ah, I didn't realize this was updated. I'll get this merged today.

**Comment by kytrinyx** [comment]
Merged in 0740b40419f0a24cd634fb7d89cd7af3f6f83057 -- thank you!

**Pull request closed without merging**
