### PR TITLE
 Add copy/expand buttons to multi file submissions

### PR DESCRIPTION
**Pull request by Motardo**
Each file in a multiple file submission will have a button to
copy the text to the clipboard and a button to expand/shrink
the code text window.

Addresses #3276

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks! Would you mind adding a screenshot of what this looks like?

**Comment by Motardo** [comment]
Here are some screenshots:  

multiclips

And expanded:  

multiclips2

Expanded showing the comments below:  

comments

Finally a close up:

close

**Comment by kytrinyx** [comment]
Awesome! And as I processed the rest of my notifications I saw that you had already added screenshots in the original issue :)

**Comment by kytrinyx** [comment]
:sparkles: :tada: :sparkles: thanks, @Motardo!

**Pull request merged**
