### PR TITLE
Add description field to Team.

### PR DESCRIPTION
**Pull request by bernardoamc**
The motivation for this PR can be found [here](https://github.com/exercism/exercism.io/issues/2944).

For now I didn't try to come up with any design decisions and would love to receive suggestions regarding the current layout.

**User profile:**
screen shot 2016-06-26 at 2 53 05 pm

**Team page with a team that has a description:**
screen shot 2016-06-26 at 2 53 21 pm

**Team page with a team without a description:**
screen shot 2016-06-26 at 2 53 34 pm

**Managing a team:**
screen shot 2016-06-26 at 3 06 39 pm

### CODE REVIEW

**Comment by bernardoamc** [comment]
@kytrinyx @NobbZ Trying to start the first iteration, am I missing something?

**Comment by NobbZ** [comment]
As I read the code you are printing the complete description on the users profile. That could be too much, especially when a user is in many teams with descriptions.

Perhaps split the description in a short and a long one, while only displaying the short on a users profile?

**Comment by bernardoamc** [comment]
I see, maybe the interface will become too cluttered indeed, but where the full description would be used  (and add value) if not in the user profile? Maybe after we implement the team search feature?

We could also work towards a better interface for displaying these teams instead of using a list, which approach do you think would be better? We can even truncate the description, lots of possibilities here. :)

**Comment by kytrinyx** [comment]
> where the full description would be used (and add value) if not in the user profile? Maybe after we implement the team search feature?

Yeah, I think the team descriptions will be most valuable with the list/search feature.

I've been wanting to change the profile to be a stream only: https://github.com/exercism/exercism.io/issues/2059

Also see: https://github.com/exercism/discussions/issues/33

**Comment by bernardoamc** [comment]
Given that the profile page is going to change, should we just keep this section about teams unchanged or even remove it entirely? I don't like the idea about having a short and a long description, one field should be enough for this.

**Comment by kytrinyx** [comment]
> should we just keep this section about teams unchanged or even remove it entirely?

Yeah, I think we could probably just leave it unchanged for now, and focus on the "going forward" stuff for teams.

**Comment by bernardoamc** [comment]
@NobbZ @kytrinyx Reverted the change on the user profile.

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
