### PR TITLE
Correct escaping

### LINKED ISSUE #3633: Mark as read for a single entry returns a 404
For example in http://exercism.io/tracks/javascript/exercises/leap
when click on the 'mark as read' button behind a single entry from another user the page redirects me to:
http://exercism.io/&#x2F;tracks&#x2F;javascript&#x2F;exercises&#x2F;leap
which shows a 'We don't have that!' 404 message.

When I reload http://exercism.io/tracks/javascript/exercises/leap the 'mark as read' button is removed

I copied the post request from my browser as a curl statement (removed the cookie) :

curl 'http://exercism.io/exercises/5404658f820445c18f7a46de5b9a9856/views?redirect=/tracks/javascript/exercises/leap' -H 'Host: exercism.io' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded' -H 'Referer: http://exercism.io/tracks/javascript/exercises/leap'  -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' --data ''

The same occurs on for example the haskell track.
The 'mark all as read' works as expected.

### PR DESCRIPTION
**Pull request by nellshamrell**
Fixes #3633

### CODE REVIEW

**Comment by kytrinyx** [comment]
Is this ever called with user-submitted data? If so we will need to escape when we do so to prevent a security hole.

**Comment by Insti** [comment]
It would be good to see a test that illustrated this change.

**Comment by nellshamrell** [comment]
Good points!  I will look into those and get those incorporated.

**Comment by kotp** [comment]
bump @nellshamrell

**Comment by kotp** [comment]
Thank you @nellshamrell

**Comment by nellshamrell** [comment]
@kotp thank you for bumping me on this - while I'd love to take it further, I unfortunately am completely swamped an unable to do further work at this time.

**Comment by kotp** [comment]
You are welcome, I may use this merge request to show someone how to take "abandoned" work and contribute, while still giving credit where credit is due.   It just shows that even contributions that aren't necessarily completed are still very much worthwhile.

**Pull request closed without merging**
