### PR TITLE
[WIP] Refactor to use trackler instead of x-api

### PR DESCRIPTION
**Pull request by kytrinyx**
Right now the exercism.io is jumping through loops to call the x-api endpoints in order to display track and exercise data. This is pretty slow, and it's also a bit of a mess.

We've extracted the core track and exercise logic into a new gem, [trackler](http://github.com/exercism/trackler), so that we can use the same code in both exercism.io and x-api efficiently.

The TL;DR is that we need to swap out calls to things that call x-api to use `Trackler` collections.

A few things we can look for are `X::` and `Xapi`.

The trackler collections are:
- `Trackler.problems`
- `Trackler.tracks`
- `Xapi.implementations`
## TODO

**If you want to help with this, then comment below with which file you're tackling, and submit your pull request to this pull request by using the`trackler` base branch instead of to `master`. (If you have questions, ask!)**

For one route at a time we need to
- swap out the code to talk to Trackler
- in the relevant tests, remove the `Xapi.stub`s
- run all of the tests to make sure that it works
- run the website and visit the actual pages that use the code that we've changed to make sure that it works with the real track data

These are some files that use x-api stuff:
- [x] `app/routes/stats.rb` - #3201
- [ ] ~~`app/presenters/tracks.rb`~~ this wasn't used anywhere
- [x] `app/routes/exercises.rb` - #3200
- [x] `app/routes/languages.rb` - #3183
- [x] `api/v1/routes/iterations.rb` - #3188
- [x] `api/v1/routes/submissions.rb` - #3173
- [x] `api/v1/routes/tracks.rb` - #3189
- [x] `lib/exercism/stream.rb` - #3204 
- [x] stats stuff in user profile - #3202 

I think we'll discover that there's more, but this at least should get us going.

Then, once we've gotten all of the code swapped out we can
- [x] delete all of the x-api related code.

I'm not exactly sure what it all is, yet, but I suspect all of these files:
- `lib/exercism/xapi.rb`
- `x/errors.rb`
- `x/exercise.rb`
- `x/problem.rb`
- `x/todos/exercise.rb`
- `x/todos/todo.rb`
- `x/track.rb`
- `x/xapi.rb`
- `x/xapi.rb

### CODE REVIEW

**Comment by kytrinyx** [comment]
@nickborromeo this is that refactoring that I mentioned, if you're interested in taking a look or helping tackle parts of it.

**Comment by mhelmetag** [comment]
I can take a crack at `api/v1/routes/submissions.rb` and related tests.

**Comment by nickborromeo** [comment]
@kytrinyx cool! Happy to help out. I can start on `app/routes/languages.rb` since I think this was what I touched last before you decided to go the gem extraction route.

**Comment by mhelmetag** [comment]
I would be willing to help someone through another one of the file changes (if they want to get their feet wet but are a bit unfamiliar with exercism, want help setting up the repo, etc). We can jump on screenhero, gitter or whatever.

**Comment by kytrinyx** [comment]
I updated the trackler gem so it can use test fixtures instead of real data. To do so, we'll add this in the test helper file:

```
Trackler.use_fixture_data
```

**Comment by kytrinyx** [comment]
@nickborromeo @mhelmetag I'll tackle the exercises route.

**Comment by kytrinyx** [comment]
I'm working on the stats endpoint.

**Comment by kytrinyx** [comment]
Heads up @nickborromeo @mhelmetag I've updated trackler to v2.0.0.0, which has a backwards incompatible change which *may* affect your open PRs.

In v1 of trackler the track.problems returned an array of strings (the slugs of the exercises that are currently active in the track), whereas now it returns actual problem objects.

**Comment by kytrinyx** [comment]
This is passing locally, failing on Travis. Investigating.

**Comment by kytrinyx** [comment]
Got it! OK, here we go. Thanks @nickborromeo @mhelmetag for your help with this!

**Pull request merged**
