### PR TITLE
Using Bundle.require instead of Bundle.setup. Fix #3249

### LINKED ISSUE #3249: Error running `bin/setup` on macOS Sierra
I just did a `git clone` of the repository and tried to follow the steps in the contributing document to get the website up and running. When executing the `bin/setup` file, the following error occured:

<pre>
fetching over the wire
rake aborted!
NameError: uninitialized constant Faraday
/Users/erikschierboom/Programming/exercism.io/lib/tasks/seed.rake:6:in `block (2 levels) in <top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/bundle:23:in `load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/bundle:23:in `<main>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/ruby_executable_hooks:15:in `eval'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:from_scratch => db:seeds:fetch
</pre>

Directly running the rake fetch using `bundle exec rake db:seeds:fetch` also fails with the same error. Any idea how to solve this?

### PR DESCRIPTION
**Pull request by esparta**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @esparta. This change would mean loading all of the gems, whether or not they're needed for a task, which I don't believe is necessary. In rake tasks we rarely need a lot of the dependencies.

I'm going to go ahead and close this, but if you have some counter-arguments that I might have missed, I'm happy to hear you out on this.

**Comment by kytrinyx** [comment]
Ah. There's a linked issue. I'm reopening this. In the future, would you please put all the information needed to evaluate a PR in the description/body of the PR itself?

**Comment by kytrinyx** [comment]
@esparta I'm going to merge this in, but I'm not sure I understand how this is better than what we had before #3214

**Comment by esparta** [comment]
Apparently the previous fix was not complete, I though using `Bundle.setup` should be enough but it is not, other rake task can be probably be broken without this. I also think is not better.
I'm thinking on work on using explicit `require`'s instead of Bundle.require, even if this mean test all the rake tasks.

**Comment by esparta** [comment]
I sent PR #3254 in order to have a better approach on the Bundle.* issue.
ping @kytrinyx

**Pull request merged**
