### PR TITLE
Fix the width of `comments` section on the submissions page.

### PR DESCRIPTION
**Pull request by nisusam**
Fixes: #3057

### CODE REVIEW

**Comment by kytrinyx** [comment]
Would you please include a screenshot of the before/after?

**Comment by nisusam** [comment]
@kytrinyx please see the following screenshots for https://github.com/exercism/exercism.io/issues/3057

**Screenshots Before Fix**

- Without Comments

submission_with_horizontal_split_mode_issue without_comment

- With Comments

submission_with_horizontal_split_mode_issue with_comments


**Screenshots After Fix**

- Without Comments

submission_without_comment resolved

- With Comments

submission_with_comments resolved

**Comment by kotp** [comment]
@nisusam it looks like some conflicts happen, can you rebase from master and resolve these?

**Comment by Insti** [comment]
Are the Gem updates a necessary part of this patch?

**Comment by nisusam** [comment]
@kotp @Insti  https://github.com/exercism/exercism.io/commit/fa5be96fef0a53a1eaf6ab8604b26aa667c946ba has updated `application.css`, which has used updated version of `bootstrap-sass` and `font-awesome-sass`.

I locked the versions of both in `Gemfile` to avoid the conflicts in future.

**Comment by bradhvr** [comment]
Hi @nisusam, just so I understand is there something I should have done differently? I'm kind of a novice with some of this. I recall having to install bootstrap-sass and font-awesome-sass separately when trying to set up my development environment.

This is from my `Gemfile.lock`:
```
bootstrap-sass (3.3.6)
font-awesome-sass (4.5.0)
```

**Comment by nisusam** [comment]
@bradhvr Since the version in Gemfile was not specified, when you ran `bundle install` bundler fetched the latest version for you, which in turn updated the compiled css.

**Comment by bradhvr** [comment]
Sorry, I'm still a little confused. Wouldn't the change to the compiled css be there because I made a change to `application.scss`? Compass updated `application.css` with my change and added the `.highlight` class.

#3072 also contains some changes to various compiled css based on my modifications.

**Comment by tejasbubane** [comment]
@bradhvr Agreed. The `application.css` should reflect your css changes, but [this file in your commit](https://github.com/exercism/exercism.io/blob/fa5be96fef0a53a1eaf6ab8604b26aa667c946ba/public/css/application.css) has bootstrap version upgraded to `3.3.7` and fontawesome to `4.6.2`.

This is a little odd since the version in [Gemfile.lock](https://github.com/exercism/exercism.io/blob/master/Gemfile.lock) is `3.3.6` for `bootstrap` and `4.5.0` for `font-awesome`.

**Comment by tejasbubane** [comment]
My initial guess is not running compass with `bundle exec` picked up the latest version of these gems installed on your machine, but I may be wrong here.

**Comment by Insti** [comment]
If the gemfile modifications are relevant, that's fine but I'd prefer to see them in a separately documented PR rather than bundled with the PR for a minor css change.

**Comment by bradhvr** [comment]
Oh ok, thanks for the explanation @tejasbubane! The CONTRIBUTING.md file doesn't say to run compass with bundle exec. Should it?

**Comment by tejasbubane** [comment]
@bradhvr I am not exactly sure if that is the cause. `bootstrap` and `font-awesome` are being required [here](https://github.com/exercism/exercism.io/blob/master/config.rb) and imported [here](https://github.com/exercism/exercism.io/blob/master/public/sass/base/import.scss).

PS: This would no longer be an issue once https://github.com/exercism/exercism.io/pull/2949 is merged.

**Comment by Insti** [comment]
> The CONTRIBUTING.md file doesn't say to run compass with bundle exec. Should it?

Yes.

**Comment by Insti** [comment]
@nisusam can you untangle the Gem updates from the comments width changes and make a new PR for them please.

**Comment by tejasbubane** [comment]
Added `bundle exec` for compass in #3075

**Comment by nisusam** [comment]
@Insti Removed the `Gemfile` changes. I'll send them in a separate PR after these changes merged.

**Comment by kytrinyx** [comment]
I've merged this locally in 3d26bbf33ed470e2457e44b6e631840507bd6968

**Pull request closed without merging**
