### PR TITLE
Only show Bugsnag message if notification occurred

### PR DESCRIPTION
**Pull request by Insti**
Only show the message that Bugsnag has been notified if Bugsnag *was* notified of the error.

### CODE REVIEW

**Comment by Insti** [comment]
I am still not seeing messages appearing in Bugsnag after #3022 has been applied.

This patch aids live debugging of this problem by only showing the "Bugsnag was notified" message if the notification was sent.

**Comment by Insti** [comment]
@kytrinyx this would be good to have merged to help debug Bugsnag notifications.

**Comment by kytrinyx** [comment]
Sorry—I totally missed this.

**Comment by kytrinyx** [comment]
I've redeployed with this change. Thanks!

**Pull request merged**
