### PR TITLE
closes #2819. Add track icon to lang pages.

### LINKED ISSUE #2819: Add track icon to language pages
We have icons for each language. We should stick it on the `http://exercism.io/languages/:track_id` page (e.g. http://exercism.io/languages/elm).

We have a helper method that gives you the icon (the second argument is the height/width in pixels).

```
<%= track_icon(track_id, 40) %>
```

The ERB file that needs to be updated is this one: `app/views/languages/language.erb`

### PR DESCRIPTION
**Pull request by amalrik**
I think 30px suits better than the default 40px for the language page.
Do you guys think that `"#{track.language} #{track_icon(track.id, 30)}"` should be in a helper?
Please let me know what you think.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I don't think it needs to be in a helper. Would you please post a screenshot of what this looks like?

**Comment by amalrik** [comment]
Sure.
screenshot_coffeescript
screenshot ruby

**Comment by kytrinyx** [comment]
On the code page we have the track icon before the language name. Should we do it the same everywhere? I am not sure which looks better: before or after.

code-page

**Comment by amalrik** [comment]
@kytrinyx 
I guess we should show the icon before the name for the sake of UX consistency. 
Here is a screenshot showing the result.
Should I update the PR? :smiley: 
screenshot_clojure

**Comment by kytrinyx** [comment]
Love it! Yes, please.

**Comment by amalrik** [comment]
There you go 😄

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
