### PR TITLE
Redisign all languages page

### PR DESCRIPTION
**Pull request by GustavoCaso**
Issue: #2634

Redesign all languages page. Show all languages active and inactive but just the problem count.

### CODE REVIEW

**Comment by GustavoCaso** [comment]
Just one thing active and inactive track  are mix in the list, do you want inactive at the bottom ?? or mix is okey ? 

image

**Comment by kytrinyx** [comment]
I'd rather have the inactive ones separated out in a section called "upcoming". I think for upcoming languages it might be useful to sort them so that the ones with the most problems are earlier than the ones with fewer problems.

What do you think of trying little boxes instead of a list? I'm going to be working on proper icons for each of the languages, so we could have an icon, the language name, and the number of exercises in that language.

**Comment by GustavoCaso** [comment]
About the ordering no problem at all.

What do you mean with boxes ? Like square grid, Right just the name but in the future there would be the icons ?

**Comment by kytrinyx** [comment]
Yeah, a square grid. As you can tell, I'm not so good at front-end :) I don't even know what things are called!

**Comment by GustavoCaso** [comment]
No problem :-) . I'll try my best to achieve it .

**Comment by kytrinyx** [comment]
We have some icons--we could use those for now. I think they're in `public/img/:track_id.png`. We could maybe put a small exercism logo if the icon is missing. (sorry, I realize that I keep adding random suggestions--I'm not tied to any of these suggestions, just thinking out loud).

**Comment by GustavoCaso** [comment]
Don't worry I'll do what I can and wait for your feedback. :+1:

**Comment by GustavoCaso** [comment]
I added the block style, I wasn't able to create a helper method for displaying the correct image, I was creating the file inside the `helpers` folder and including it in the `helper` file but it didn't work, weird.

A part from that i looks better, and with the new icons would look great.

screen shot 2015-12-20 at 20 49 59

**Comment by kytrinyx** [comment]
> I wasn't able to create a helper method for displaying the correct image

They also have to be registered with the app. See `app/routes/core.rb` lines 34-44.

**Comment by kytrinyx** [comment]
Yeah, this looks excellent! Do you want to do the helper file thing before I merge this?

**Comment by GustavoCaso** [comment]
Sure to have more clean code

**Comment by GustavoCaso** [comment]
@kytrinyx I have added the helper method feel free to merge it when ever you want.

**Comment by kytrinyx** [comment]
Nice, thanks so much!

**Pull request merged**
