### PR TITLE
Delete documentation that has moved

### PR DESCRIPTION
**Pull request by kytrinyx**
We've created a docs repository (https://github.com/exercism/docs),
and have started moving all of our project-level documentation there.

The documentation left in this repository should be specific to
contributing to this repository.

I'm going to go through the documentation in the docs repository as well and make sure the links are all working, and the documentation still makes sense.

### CODE REVIEW

**Comment by Insti** [comment]
Is there a matching PR that adds all these files to the docs repository?

**Comment by kytrinyx** [comment]
Most of them are already there, and I have a branch with the remaining ones. I want to do a couple of tweaks in that branch today before submitting it.

**Comment by Insti** [comment]
There's so much going on here I don't think it's practical to review.
I liked the idea of 1:1 Add:Delete PR pairs.
But I trust you know what you're doing.

**Comment by kytrinyx** [comment]
Eh, yeah, good point. I'll make individual PRs where I can point to the matching docs.

**Pull request closed without merging**
