### PR TITLE
Add dailies view

### PR DESCRIPTION
**Pull request by bmulvihill**
Adds view for Daily model

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks!

**Comment by kytrinyx** [comment]
I had to revert this PR--the query `SELECT * FROM dailies WHERE user_id=$1 LIMIT 5` takes down the database for users with a lot of data.

**Comment by bmulvihill** [comment]
@kytrinyx Ahh! I did forget to exclude exercises where last_iteration_at >  30days, which should significantly increase the speed of the query.  I am going to research some optimizations and will open a new PR if you still want to go in this direction.

**Comment by kytrinyx** [comment]
Yeah, I'd love to keep going down this path. Constraining to the last 30 days should help a lot... and some indices too.

**Pull request merged**
