### PR TITLE
changing default of blue to grey in navigation buttons.

### PR DESCRIPTION
**Pull request by gusseting**
As per [https://github.com/exercism/discussions/issues/34](issue 34) the default has been changed from blue to grey in the exercism.scss file and dependent files in order to change the navigation colors to those in line with exercism branding.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I've pulled this down to look at it locally, and this looks great! I saw some discussion in your slack channel that suggested that you weren't ready to merge. Did you get everything that you wanted straightened out?

**Comment by gusseting** [comment]
@kytrinyx all straightened out - so please do merge.

**Comment by kytrinyx** [comment]
:heart: :heart: :sparkles: thank you!

**Comment by Insti** [comment]
I'm *really* disliking the grey buttons. It makes them all look like they are disabled.
Can we have a bit of color back in them please?

**Pull request merged**
